import { Platform } from 'react-native';

export const IS_WEB = Platform.OS === 'web';

export const EDITORIAL_FONT_FAMILY = Platform.select({
  web: 'Georgia, "Times New Roman", serif',
  ios: 'Georgia',
  android: 'serif',
  default: undefined,
});

export const SIDEBAR_MENU_ITEMS = [
  { key: 'latest', labelKey: 'latestNews', fallbackLabel: 'Latest News', icon: 'flame-outline', accentColor: '#fb923c', surfaceColor: '#fff7ed' },
  { key: 'states', labelKey: 'news', fallbackLabel: 'News', icon: 'newspaper-outline', accentColor: '#ec4899', surfaceColor: '#fdf2f8' },
  { key: 'politics', labelKey: 'politics', fallbackLabel: 'Politics', icon: 'library-outline', accentColor: '#0ea5e9', surfaceColor: '#eff6ff' },
  { key: 'elections', labelKey: 'elections', fallbackLabel: 'Elections', icon: 'ballot-outline', accentColor: '#22c55e', surfaceColor: '#effcf3' },
  { key: 'viral', labelKey: 'viral', fallbackLabel: 'Viral', icon: 'megaphone-outline', accentColor: '#3b82f6', surfaceColor: '#eff6ff' },
  { key: 'astrology', labelKey: 'astrology', fallbackLabel: 'Astrology', icon: 'sparkles-outline', accentColor: '#8b5cf6', surfaceColor: '#f5f3ff' },
  { key: 'horoscope_hindi', labelKey: 'horoscopeHindi', fallbackLabel: 'Horoscope in Hindi', icon: 'moon-outline', accentColor: '#f43f5e', surfaceColor: '#fff1f2' },
  { key: 'horoscope_english', labelKey: 'horoscopeEnglish', fallbackLabel: 'Horoscope in English', icon: 'planet-outline', accentColor: '#4f46e5', surfaceColor: '#eef2ff' },
  { key: 'latest_political', labelKey: 'latestPoliticalNews', fallbackLabel: 'Latest Political News', icon: 'albums-outline', accentColor: '#10b981', surfaceColor: '#ecfdf5' },
];

export const STATE_LABELS = [
  'Andaman And Nicobar Islands', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam',
  'Bihar', 'Chandigarh', 'Chhattisgarh', 'Dadra And Nagar Haveli And Daman And Diu',
  'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu And Kashmir',
  'Jharkhand', 'Karnataka', 'Kerala', 'Ladakh', 'Lakshadweep', 'Madhya Pradesh',
  'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha',
  'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana',
  'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
];

export const STATE_CARD_COLORS = ['#fb923c', '#8b5cf6', '#f97316', '#ec4899', '#0ea5e9', '#f59e0b', '#3b82f6'];

export const CATEGORY_COLOR_MAP = {
  latest: '#f97316',
  politics: '#0ea5e9',
  elections: '#22c55e',
  viral: '#3b82f6',
  astrology: '#8b5cf6',
  horoscope_hindi: '#f43f5e',
  horoscope_english: '#4f46e5',
  latest_political: '#10b981',
};

export const FEATURED_STATE_OPTIONS = ['Maharashtra', 'Bihar', 'Uttar Pradesh', 'Delhi', 'Karnataka', 'West Bengal'];

export const FALLBACK_DISTRICT_MAP = {
  Bihar: ['Araria', 'Aurangabad', 'Banka', 'Begusarai', 'Bhagalpur', 'Buxar', 'Darbhanga', 'Gaya'],
  Delhi: ['New Delhi', 'Central Delhi', 'East Delhi', 'North Delhi', 'South Delhi', 'West Delhi'],
  Gujarat: ['Ahmedabad', 'Rajkot', 'Surat', 'Vadodara', 'Bhavnagar', 'Kutch'],
  Karnataka: ['Bengaluru Urban', 'Mysuru', 'Mangaluru', 'Hubballi', 'Belagavi', 'Ballari'],
  'Madhya Pradesh': ['Bhopal', 'Indore', 'Jabalpur', 'Gwalior', 'Ujjain', 'Sagar'],
  Maharashtra: ['Mumbai', 'Pune', 'Nagpur', 'Nashik', 'Thane', 'Kolhapur', 'Aurangabad', 'Solapur'],
  Rajasthan: ['Jaipur', 'Jodhpur', 'Udaipur', 'Ajmer', 'Kota', 'Bikaner'],
  'Tamil Nadu': ['Chennai', 'Coimbatore', 'Madurai', 'Salem', 'Tiruchirappalli', 'Vellore'],
  'Uttar Pradesh': ['Lucknow', 'Kanpur', 'Meerut', 'Varanasi', 'Prayagraj', 'Agra', 'Noida', 'Gorakhpur'],
  'West Bengal': ['Kolkata', 'Howrah', 'Siliguri', 'Durgapur', 'Asansol', 'Darjeeling'],
};

export const DEMO_STORIES = [
  {
    id: 'demo-story-1',
    title: 'Civic volunteers expand RTI help camps across Meerut wards',
    excerpt: 'Residents are getting faster guidance on filing transparency requests and tracking local complaints.',
    description: 'The RTI help desk in Meerut has expanded into multiple wards this week, bringing assisted filing, follow-up support, and awareness sessions closer to citizens.',
    category: 'Latest Political News',
    menuTags: ['latest', 'politics', 'latest_political'],
    state: 'Uttar Pradesh', district: 'Meerut', taluka: 'Meerut City',
    author_name: 'Sachin Shivalia', author_profile_image: 'https://i.pravatar.cc/96?u=sachin-shivalia',
    author_seat_name: 'Reporter', author_role_label: 'Field Correspondent', author_is_premium: true,
    image: 'https://picsum.photos/seed/rti-latest-1/900/640', images: ['https://picsum.photos/seed/rti-latest-1/900/640'],
    date: '05 May 2026', publishedAgo: '6 min ago', views: 20, likes: 4, comments: 2, shares: 1,
  },
  {
    id: 'demo-story-2',
    title: 'Municipal reply tracker launches in Pune for pending RTI cases',
    excerpt: 'A new civic dashboard is helping applicants monitor delayed responses from multiple local departments.',
    description: 'Citizen groups in Pune have rolled out a ward-wise tracker that highlights overdue replies, pending appeals, and frequently requested civic records.',
    category: 'Latest News', menuTags: ['latest'],
    state: 'Maharashtra', district: 'Pune', taluka: 'Pune City',
    author_name: 'Nikita Joshi', author_profile_image: 'https://i.pravatar.cc/96?u=nikita-joshi',
    author_seat_name: 'City Desk', author_is_premium: false,
    image: 'https://picsum.photos/seed/rti-latest-2/900/640', images: ['https://picsum.photos/seed/rti-latest-2/900/640'],
    date: '05 May 2026', publishedAgo: '18 min ago', views: 51, likes: 12, comments: 4, shares: 3,
  },
  {
    id: 'demo-story-3',
    title: 'Election watch teams in Patna review manifesto promises on transparency',
    excerpt: 'Citizens and researchers are comparing campaign claims with department-level disclosure records.',
    description: 'A volunteer election watch initiative in Bihar is compiling RTI-based reports to compare campaign promises against existing governance records.',
    category: 'Elections', menuTags: ['latest', 'elections', 'latest_political', 'politics'],
    state: 'Bihar', district: 'Patna', taluka: 'Patna Sadar',
    author_name: 'Apoorva Singh', author_profile_image: 'https://i.pravatar.cc/96?u=apoorva-singh',
    author_seat_name: 'Election Desk', author_is_premium: true,
    image: 'https://picsum.photos/seed/rti-election-1/900/640', images: ['https://picsum.photos/seed/rti-election-1/900/640'],
    date: '05 May 2026', publishedAgo: '32 min ago', views: 73, likes: 18, comments: 5, shares: 4,
  },
  {
    id: 'demo-story-4',
    title: "Short civic explainer from Delhi turns into the day's most shared RTI clip",
    excerpt: 'A compact video about public records access has gone viral across neighborhood groups.',
    description: 'The clip breaks down how to ask precise questions under the RTI Act and why document-based civic reporting matters.',
    category: 'Viral', menuTags: ['latest', 'viral'],
    state: 'Delhi', district: 'Central Delhi', taluka: 'New Delhi',
    author_name: 'Raghav Mehta', author_profile_image: 'https://i.pravatar.cc/96?u=raghav-mehta',
    author_seat_name: 'Digital Desk', author_is_premium: false,
    image: 'https://picsum.photos/seed/rti-viral-1/900/640', images: ['https://picsum.photos/seed/rti-viral-1/900/640'],
    date: '05 May 2026', publishedAgo: '43 min ago', views: 124, likes: 30, comments: 8, shares: 9,
  },
  {
    id: 'demo-story-5',
    title: 'Jaipur desk publishes weekly astrology bulletin for civic readers',
    excerpt: 'A light-format feature mixes astro trends with newsroom scheduling and audience favorites.',
    description: 'The Jaipur editorial desk has launched a weekly astrology-style bulletin that appears alongside public-interest and lifestyle coverage.',
    category: 'Astrology', menuTags: ['latest', 'astrology'],
    state: 'Rajasthan', district: 'Jaipur', taluka: 'Jaipur City',
    author_name: 'Priyal Bhatia', author_profile_image: 'https://i.pravatar.cc/96?u=priyal-bhatia',
    author_seat_name: 'Features Desk', author_is_premium: false,
    image: 'https://picsum.photos/seed/rti-astrology-1/900/640', images: ['https://picsum.photos/seed/rti-astrology-1/900/640'],
    date: '05 May 2026', publishedAgo: '55 min ago', views: 39, likes: 7, comments: 3, shares: 2,
  },
  {
    id: 'demo-story-6',
    title: 'Hindi horoscope page for RTI readers draws strong evening traffic in Bhopal',
    excerpt: 'Audience analytics show strong repeat visits for the new Hindi-format horoscope section.',
    description: 'The Bhopal editorial desk is pairing concise rashifal-style updates with public-interest reading suggestions for its Hindi audience.',
    category: 'Horoscope in Hindi', menuTags: ['latest', 'horoscope_hindi', 'astrology'],
    state: 'Madhya Pradesh', district: 'Bhopal', taluka: 'Bhopal',
    author_name: 'Sonal Verma', author_profile_image: 'https://i.pravatar.cc/96?u=sonal-verma',
    author_seat_name: 'Hindi Features', author_is_premium: false,
    image: 'https://picsum.photos/seed/rti-hindi-horoscope-1/900/640', images: ['https://picsum.photos/seed/rti-hindi-horoscope-1/900/640'],
    date: '05 May 2026', publishedAgo: '1 hr ago', views: 45, likes: 11, comments: 4, shares: 2,
  },
  {
    id: 'demo-story-7',
    title: 'English horoscope digest joins the Bengaluru morning briefing lineup',
    excerpt: 'The lifestyle micro-feed is now bundled with civic news for English-first readers.',
    description: "Editors in Bengaluru are testing a short English horoscope module within the city's first-read feed to improve repeat readership.",
    category: 'Horoscope in English', menuTags: ['latest', 'horoscope_english', 'astrology'],
    state: 'Karnataka', district: 'Bengaluru Urban', taluka: 'Bengaluru',
    author_name: 'Anika Rao', author_profile_image: 'https://i.pravatar.cc/96?u=anika-rao',
    author_seat_name: 'Morning Briefing', author_is_premium: false,
    image: 'https://picsum.photos/seed/rti-english-horoscope-1/900/640', images: ['https://picsum.photos/seed/rti-english-horoscope-1/900/640'],
    date: '05 May 2026', publishedAgo: '1 hr ago', views: 41, likes: 9, comments: 2, shares: 1,
  },
  {
    id: 'demo-story-8',
    title: 'Kolkata political round-up focuses on file access, spending, and tender visibility',
    excerpt: 'Reporters are tracing how new decisions connect to pending public document requests.',
    description: 'The state political desk has prepared a detailed accountability round-up covering procurement questions, disclosure timelines, and committee minutes.',
    category: 'Politics', menuTags: ['latest', 'politics', 'latest_political'],
    state: 'West Bengal', district: 'Kolkata', taluka: 'Kolkata',
    author_name: 'Arijit Sen', author_profile_image: 'https://i.pravatar.cc/96?u=arijit-sen',
    author_seat_name: 'Political Bureau', author_is_premium: true,
    image: 'https://picsum.photos/seed/rti-politics-1/900/640', images: ['https://picsum.photos/seed/rti-politics-1/900/640'],
    date: '05 May 2026', publishedAgo: '1 hr ago', views: 92, likes: 22, comments: 7, shares: 4,
  },
  {
    id: 'demo-story-9',
    title: 'Assam district election notes spotlight unanswered information requests',
    excerpt: 'Candidates are being measured against their record on disclosure and local access.',
    description: 'A constituency-level transparency tracker in Assam is highlighting unresolved RTI matters as campaign narratives intensify.',
    category: 'Elections', menuTags: ['latest', 'elections', 'latest_political', 'politics'],
    state: 'Assam', district: 'Kamrup Metropolitan', taluka: 'Guwahati',
    author_name: 'Junaid Ahmed', author_profile_image: 'https://i.pravatar.cc/96?u=junaid-ahmed',
    author_seat_name: 'Election Watch', author_is_premium: false,
    image: 'https://picsum.photos/seed/rti-election-2/900/640', images: ['https://picsum.photos/seed/rti-election-2/900/640'],
    date: '05 May 2026', publishedAgo: '1 hr ago', views: 66, likes: 16, comments: 5, shares: 3,
  },
  {
    id: 'demo-story-10',
    title: 'Ahmedabad civic complaint story becomes a fast-moving viral share chain',
    excerpt: 'Short explainers and maps made the story easy to circulate through local groups.',
    description: 'The newsroom package tied together ward maps, RTI document references, and a short community explainer, which quickly gained traction.',
    category: 'Viral', menuTags: ['latest', 'viral'],
    state: 'Gujarat', district: 'Ahmedabad', taluka: 'Ahmedabad City',
    author_name: 'Khushi Patel', author_profile_image: 'https://i.pravatar.cc/96?u=khushi-patel',
    author_seat_name: 'Community Desk', author_is_premium: false,
    image: 'https://picsum.photos/seed/rti-viral-2/900/640', images: ['https://picsum.photos/seed/rti-viral-2/900/640'],
    date: '05 May 2026', publishedAgo: '2 hr ago', views: 138, likes: 34, comments: 10, shares: 11,
  },
  {
    id: 'demo-story-11',
    title: 'Chennai policy reporters build a latest political tracker around civic files',
    excerpt: 'The special page follows ministers, departments, and pending records requests in one stream.',
    description: 'The Chennai bureau has launched a compact tracker linking policy decisions with department records, public audits, and local RTI replies.',
    category: 'Latest Political News', menuTags: ['latest', 'politics', 'latest_political'],
    state: 'Tamil Nadu', district: 'Chennai', taluka: 'Chennai',
    author_name: 'Meera Krishnan', author_profile_image: 'https://i.pravatar.cc/96?u=meera-krishnan',
    author_seat_name: 'State Bureau', author_is_premium: true,
    image: 'https://picsum.photos/seed/rti-politics-2/900/640', images: ['https://picsum.photos/seed/rti-politics-2/900/640'],
    date: '05 May 2026', publishedAgo: '2 hr ago', views: 84, likes: 19, comments: 6, shares: 5,
  },
  {
    id: 'demo-story-12',
    title: 'Kochi public records feature highlights citizen wins in transport approvals',
    excerpt: 'Readers are engaging with practical examples of how RTI follow-ups unlocked pending files.',
    description: 'The Kochi desk has spotlighted a series of public records requests that helped residents access delayed paperwork and transport approvals.',
    category: 'Latest News', menuTags: ['latest'],
    state: 'Kerala', district: 'Ernakulam', taluka: 'Kochi',
    author_name: 'Renu Thomas', author_profile_image: 'https://i.pravatar.cc/96?u=renu-thomas',
    author_seat_name: 'Public Interest Desk', author_is_premium: false,
    image: 'https://picsum.photos/seed/rti-latest-3/900/640', images: ['https://picsum.photos/seed/rti-latest-3/900/640'],
    date: '05 May 2026', publishedAgo: '2 hr ago', views: 58, likes: 13, comments: 4, shares: 2,
  },
  {
    id: 'demo-story-13',
    title: 'Hyderabad governance tracker adds a latest political bulletin for city readers',
    excerpt: 'The new section bundles public file trails with quick city-level governance briefs.',
    description: 'Editors in Hyderabad are packaging governance notes, pending disclosures, and RTI follow-up stories into a single political digest.',
    category: 'Latest Political News', menuTags: ['latest', 'politics', 'latest_political'],
    state: 'Telangana', district: 'Hyderabad', taluka: 'Hyderabad',
    author_name: 'Tarun Goud', author_profile_image: 'https://i.pravatar.cc/96?u=tarun-goud',
    author_seat_name: 'Governance Desk', author_is_premium: false,
    image: 'https://picsum.photos/seed/rti-politics-3/900/640', images: ['https://picsum.photos/seed/rti-politics-3/900/640'],
    date: '05 May 2026', publishedAgo: '2 hr ago', views: 63, likes: 15, comments: 4, shares: 3,
  },
];