const SITE_COPY = {
  en: {
    common: {
      home: 'Home',
      about: 'About',
      feed: 'Feed',
      rti: 'What Is RTI',
      rtiShort: 'RTI',
      laws: 'Important Laws',
      contact: 'Contact',
      signUp: 'Sign Up',
      profile: 'Profile',
      dashboard: 'Dashboard',
      logout: 'Logout',
      login: 'Login',
      aboutUs: 'About Us',
      contactUs: 'Contact Us',
      trendingNews: 'Trending News',
      stateCoverage: 'State Coverage',
      quickLinks: 'Quick Links',
      aboutRtiNews: 'About RTI News',
      followOn: 'Follow RTI app on',
      latestNews: 'Latest News',
      newsByState: 'News by State',
      news: 'News',
      politics: 'Politics',
      elections: 'Elections',
      viral: 'Viral',
      astrology: 'Astrology',
      horoscopeHindi: 'Horoscope in Hindi',
      horoscopeEnglish: 'Horoscope in English',
      latestPoliticalNews: 'Latest Political News',
      like: 'Like',
      comment: 'Comment',
      share: 'Share',
      likes: 'Likes',
      views: 'Views',
      comments: 'Comments',
      shares: 'Shares',
      viewAll: 'View All',
      viewPost: 'View Post',
      reporter: 'Reporter',
      video: 'VIDEO',
      terms: 'Terms and Conditions',
      privacy: 'Privacy Policy',
      teamCareer: 'Team and Career',
      refund: 'Refund and Cancellation Policy',
    },
    footer: {
      brandTitle: 'RTI News Network',
      brandSubtitle: 'Public-interest reporting for citizens across India',
      contactLine: 'Contact Us: info@rtinews.in',
    },
    home: {
      searchFeedPlaceholder: 'Search title, state, reporter, or category',
      searchStatePlaceholder: 'Search a state or union territory',
      resetFeed: 'Reset Feed',
      stateDirectoryTitle: 'Explore news from',
      stateDirectoryDescription: 'Tap any state or union territory to open its related local RTI news feed.',
      selectedPlaceEyebrow: 'Selected Place',
      selectedPlaceTitleSuffix: 'and nearby updates',
      selectedPlaceSubtitleWithData: 'District and city names appear below. Tap any place to refresh the preview image.',
      selectedPlaceSubtitleEmpty: 'Local place names will appear here as soon as stories are available.',
      choosePlaceEyebrow: 'Choose Place',
      choosePlaceTitle: 'Pick a state to load district names',
      choosePlaceSubtitle: 'Use the state list on the left or the quick buttons below. Once you choose a place, related city and district names will appear here.',
      focusedMenuSubtitle: 'Login stays pinned here. Open the News section when you want to choose a state and browse district names.',
      latestEyebrow: 'Latest Work',
      latestTitle: 'Login and track the latest RTI updates',
      latestSubtitle: 'This area stays clean on the latest section. Open News from the sidebar to switch into place-wise browsing.',
      helperText: 'Open the News section to show place buttons here.',
    },
    about: {
      heroBadge: "India's #1 RTI News Portal",
      heroTitle: 'About RTI News',
      heroSubtitle: 'Empowering citizens with the Right to Information since 2015.',
      missionLabel: 'OUR MISSION',
      missionTitle: "Making Transparency Everyone's Right",
      valuesLabel: 'WHAT WE STAND FOR',
      valuesTitle: 'Our Core Values',
      teamLabel: 'THE PEOPLE BEHIND THE STORIES',
      teamTitle: 'Meet Our Team',
      journeyLabel: 'OUR JOURNEY',
      journeyTitle: 'Milestones',
      ctaBadge: 'Join Our Mission',
      ctaTitle: 'Be a Voice for Transparency & Justice',
      ctaDescription: "Whether you're a journalist, RTI activist, lawyer, or a concerned citizen, we welcome you to contribute to India's largest RTI news platform.",
      joinReporter: 'Join as Reporter',
      contactUs: 'Contact Us',
      questionsTitle: 'Have Questions?',
      questionsSubtitle: 'Reach out to our editorial team anytime.',
    },
    contact: {
      heroBadge: 'GET IN TOUCH',
      heroTitle: 'Contact Us',
      heroSubtitle: "We'd love to hear from you. Reach out with your queries, feedback, or news tips.",
      ourLocation: 'Our Location',
      getDirections: 'Get Directions ->',
      contactInformation: 'Contact Information',
      phoneNumber: 'Phone Number',
      callForInquiries: 'Call us for inquiries',
      emailAddress: 'Email Address',
      respondWithinDay: "We'll respond within 24 hours",
      workingHours: 'Working Hours',
      sundayClosed: 'Sunday Closed',
      officeAddress: 'Office Address',
      faqTitle: 'Frequently Asked Questions',
      formTitle: 'Send us a Message',
      formSubtitle: 'Have a question or want to share a news tip? Fill out the form below.',
      fullName: 'Full Name',
      phone: 'Phone Number',
      subject: 'Subject',
      message: 'Message',
      namePlaceholder: 'Enter your full name',
      phonePlaceholder: 'Enter your phone number',
      emailPlaceholder: 'Enter your email address',
      messagePlaceholder: 'Write your message here...',
      selectSubject: 'Select a subject',
      selectSubjectTitle: 'Select a Subject',
      sendMessage: 'Send Message ->',
      errorTitle: 'Error',
      errorRequiredFields: 'Please fill all required fields.',
      successTitle: 'Success',
      successMessage: 'Your message has been sent!',
      subjects: ['General Inquiry', 'News Tip', 'RTI Assistance', 'Feedback', 'Partnership', 'Other'],
    },
    laws: {
      heroTitle: 'Important Laws',
      heroSubtitle: 'RTI Act and related important laws every citizen should know.',
      sectionLabel: 'IMPORTANT LAWS & ACTS',
      sectionTitle: 'Important Laws',
      applicationFee: 'Application Fee',
      responseTime: 'Response Time',
      lifeLiberty: 'Life & Liberty',
      bplCitizens: 'BPL Citizens',
      stepsTitle: 'RTI Application Process',
      cicTitle: 'Central Information Commission',
    },
    rti: {
      badge: 'What is RTI?',
      headerTitle: 'Simple and Easy Method to Obtain Information under RTI',
      headerDescription: 'Detailed information on how to file an RTI application, how much time it takes, what the fee is, how to appeal, and the duties and responsibilities of Public Information Officers.',
      contentsTitle: 'Contents',
      infoSubtitle: 'Right to Information',
      infoTitle: 'It is your right to know the method of obtaining information under RTI in Maharashtra State',
      infoDescription: 'A common citizen can use RTI to request information from the government. It is important to have knowledge of the correct application, timely appeal, and necessary documents.',
      faqTitle: 'Frequently Asked Questions',
      questionLabel: 'Question',
      responsibilitiesTitle: 'Public Information Officer Duties and Responsibilities',
      responsibilitiesSubtitle: 'Action to be taken by the Public Information Officer within the first 5 days of receiving an application for information from citizens',
      readMore: 'Read More',
      showLess: 'Show Less',
    },
    feed: {
      uploadTitle: 'News Post',
      mediaBoxText: 'Add video / photo',
      mediaBoxSub: '(choose from gallery)',
      headlinePlaceholder: 'Headline (e.g. RTI revealed the road issue!)',
      captionPlaceholder: 'Write your RTI story in detail...',
      categoryLabel: 'Category:',
      cancel: 'Cancel',
      post: 'Post',
      commentsTitle: 'Comments',
      noComments: 'Be the first to comment!',
      commentPlaceholder: 'Write a comment...',
      close: 'Close',
      loginAsYou: 'You',
      viewAllCommentsPrefix: 'View all',
      viewAllCommentsSuffix: 'comments',
      tags: {
        successStory: 'Success Story',
        applicationFiled: 'Application Filed',
        victory: 'Victory',
        question: 'Question',
        officialUpdate: 'Official Update',
        corruptionExposed: 'Corruption Exposed',
      },
      captionRequiredTitle: 'Caption required',
      captionRequiredMessage: 'Please write something before posting.',
      showLess: 'Show less',
      showMore: 'Show more',
    },
  },
  hi: {
    common: {
      home: 'होम',
      about: 'हमारे बारे में',
      feed: 'फीड',
      rti: 'RTI क्या है',
      rtiShort: 'RTI',
      laws: 'महत्वपूर्ण कानून',
      contact: 'संपर्क',
      signUp: 'साइन अप',
      profile: 'प्रोफाइल',
      dashboard: 'डैशबोर्ड',
      logout: 'लॉगआउट',
      login: 'लॉगिन',
      aboutUs: 'हमारे बारे में',
      contactUs: 'संपर्क करें',
      trendingNews: 'ट्रेंडिंग न्यूज़',
      stateCoverage: 'राज्य कवरेज',
      quickLinks: 'क्विक लिंक्स',
      aboutRtiNews: 'RTI News के बारे में',
      followOn: 'RTI ऐप को फॉलो करें',
      latestNews: 'ताज़ा खबरें',
      newsByState: 'राज्यवार समाचार',
      news: 'समाचार',
      politics: 'राजनीति',
      elections: 'चुनाव',
      viral: 'वायरल',
      astrology: 'ज्योतिष',
      horoscopeHindi: 'हिंदी राशिफल',
      horoscopeEnglish: 'अंग्रेज़ी राशिफल',
      latestPoliticalNews: 'ताज़ा राजनीतिक समाचार',
      like: 'लाइक',
      comment: 'टिप्पणी',
      share: 'शेयर',
      likes: 'लाइक्स',
      views: 'व्यूज़',
      comments: 'टिप्पणियाँ',
      shares: 'शेयर',
      viewAll: 'पूरा देखें',
      viewPost: 'पोस्ट देखें',
      reporter: 'रिपोर्टर',
      video: 'वीडियो',
      terms: 'नियम और शर्तें',
      privacy: 'गोपनीयता नीति',
      teamCareer: 'टीम और करियर',
      refund: 'रिफंड और कैंसलेशन नीति',
    },
    footer: {
      brandSubtitle: 'भारत के नागरिकों के लिए जनहित रिपोर्टिंग',
      contactLine: 'संपर्क करें: info@rtinews.in',
    },
    home: {
      searchFeedPlaceholder: 'शीर्षक, राज्य, रिपोर्टर या श्रेणी खोजें',
      searchStatePlaceholder: 'राज्य या केंद्र शासित प्रदेश खोजें',
      resetFeed: 'फीड रीसेट करें',
      stateDirectoryTitle: 'यहां से खबरें देखें',
      stateDirectoryDescription: 'किसी भी राज्य या केंद्र शासित प्रदेश पर टैप करके उससे जुड़ी RTI न्यूज़ फीड खोलें।',
      selectedPlaceEyebrow: 'चुना गया स्थान',
      selectedPlaceTitleSuffix: 'और आसपास के अपडेट',
      selectedPlaceSubtitleWithData: 'जिले और शहरों के नाम नीचे दिख रहे हैं। प्रीव्यू बदलने के लिए किसी जगह पर टैप करें।',
      selectedPlaceSubtitleEmpty: 'जैसे ही कहानियां उपलब्ध होंगी, स्थानीय जगहों के नाम यहां दिखाई देंगे।',
      choosePlaceEyebrow: 'स्थान चुनें',
      choosePlaceTitle: 'जिले देखने के लिए राज्य चुनें',
      choosePlaceSubtitle: 'बाईं तरफ की राज्य सूची या नीचे के क्विक बटन का उपयोग करें। स्थान चुनते ही उससे जुड़े जिले और शहर यहां दिखेंगे।',
      focusedMenuSubtitle: 'यहां लॉगिन पिन रहेगा। राज्य और जिले देखने के लिए न्यूज़ सेक्शन खोलें।',
      latestEyebrow: 'ताज़ा अपडेट',
      latestTitle: 'लॉगिन करें और नवीनतम RTI अपडेट देखें',
      latestSubtitle: 'लेटेस्ट सेक्शन पर यह हिस्सा साफ रखा गया है। राज्यवार ब्राउज़िंग के लिए साइडबार से न्यूज़ खोलें।',
      helperText: 'यहां जगह के बटन दिखाने के लिए न्यूज़ सेक्शन खोलें।',
    },
    about: {
      heroBadge: 'भारत का #1 RTI न्यूज़ पोर्टल',
      heroTitle: 'RTI News के बारे में',
      heroSubtitle: '2015 से सूचना के अधिकार के साथ नागरिकों को सशक्त बना रहे हैं।',
      missionLabel: 'हमारा मिशन',
      missionTitle: 'पारदर्शिता को सबका अधिकार बनाना',
      valuesLabel: 'हम किन मूल्यों पर खड़े हैं',
      valuesTitle: 'हमारे मूल मूल्य',
      teamLabel: 'कहानियों के पीछे के लोग',
      teamTitle: 'हमारी टीम से मिलें',
      journeyLabel: 'हमारी यात्रा',
      journeyTitle: 'मुख्य पड़ाव',
      ctaBadge: 'हमारे मिशन से जुड़ें',
      ctaTitle: 'पारदर्शिता और न्याय की आवाज़ बनें',
      ctaDescription: 'चाहे आप पत्रकार हों, RTI कार्यकर्ता, वकील या जागरूक नागरिक, हम आपको भारत के सबसे बड़े RTI न्यूज़ प्लेटफॉर्म में योगदान देने के लिए आमंत्रित करते हैं।',
      joinReporter: 'रिपोर्टर बनें',
      contactUs: 'संपर्क करें',
      questionsTitle: 'कोई सवाल है?',
      questionsSubtitle: 'हमारी संपादकीय टीम से कभी भी संपर्क करें।',
    },
    contact: {
      heroBadge: 'संपर्क में रहें',
      heroTitle: 'संपर्क करें',
      heroSubtitle: 'अपने प्रश्न, सुझाव या न्यूज़ टिप के लिए हमसे जुड़ें।',
      ourLocation: 'हमारा स्थान',
      getDirections: 'दिशा देखें ->',
      contactInformation: 'संपर्क जानकारी',
      phoneNumber: 'फोन नंबर',
      callForInquiries: 'पूछताछ के लिए कॉल करें',
      emailAddress: 'ईमेल पता',
      respondWithinDay: 'हम 24 घंटे के भीतर जवाब देंगे',
      workingHours: 'कार्य समय',
      sundayClosed: 'रविवार बंद',
      officeAddress: 'कार्यालय का पता',
      faqTitle: 'अक्सर पूछे जाने वाले सवाल',
      formTitle: 'हमें संदेश भेजें',
      formSubtitle: 'कोई सवाल है या न्यूज़ टिप साझा करनी है? नीचे दिया गया फॉर्म भरें।',
      fullName: 'पूरा नाम',
      phone: 'फोन नंबर',
      subject: 'विषय',
      message: 'संदेश',
      namePlaceholder: 'अपना पूरा नाम लिखें',
      phonePlaceholder: 'अपना फोन नंबर लिखें',
      emailPlaceholder: 'अपना ईमेल पता लिखें',
      messagePlaceholder: 'अपना संदेश यहां लिखें...',
      selectSubject: 'विषय चुनें',
      selectSubjectTitle: 'विषय चुनें',
      sendMessage: 'संदेश भेजें ->',
      errorTitle: 'त्रुटि',
      errorRequiredFields: 'कृपया सभी जरूरी फ़ील्ड भरें।',
      successTitle: 'सफलता',
      successMessage: 'आपका संदेश भेज दिया गया है!',
      subjects: ['सामान्य पूछताछ', 'न्यूज़ टिप', 'RTI सहायता', 'फीडबैक', 'साझेदारी', 'अन्य'],
    },
    laws: {
      heroTitle: 'महत्वपूर्ण कानून',
      heroSubtitle: 'RTI अधिनियम और संबंधित महत्वपूर्ण कानून जिन्हें हर नागरिक को जानना चाहिए।',
      sectionLabel: 'महत्वपूर्ण कानून और अधिनियम',
      sectionTitle: 'महत्वपूर्ण कानून',
      applicationFee: 'आवेदन शुल्क',
      responseTime: 'उत्तर का समय',
      lifeLiberty: 'जीवन और स्वतंत्रता',
      bplCitizens: 'BPL नागरिक',
      stepsTitle: 'RTI आवेदन प्रक्रिया',
      cicTitle: 'केंद्रीय सूचना आयोग',
    },
    rti: {
      badge: 'RTI क्या है?',
      headerTitle: 'RTI के तहत सूचना पाने का सरल और आसान तरीका',
      headerDescription: 'RTI आवेदन कैसे करें, कितना समय लगता है, शुल्क क्या है, अपील कैसे करें और लोक सूचना अधिकारियों की जिम्मेदारियां क्या हैं, इसकी विस्तृत जानकारी।',
      contentsTitle: 'विषय सूची',
      infoSubtitle: 'सूचना का अधिकार',
      infoTitle: 'महाराष्ट्र राज्य में RTI के तहत सूचना पाने की विधि जानना आपका अधिकार है',
      infoDescription: 'एक सामान्य नागरिक RTI का उपयोग करके सरकार से सूचना मांग सकता है। सही आवेदन, समय पर अपील और आवश्यक दस्तावेजों की जानकारी होना बहुत जरूरी है।',
      faqTitle: 'अक्सर पूछे जाने वाले सवाल',
      questionLabel: 'प्रश्न',
      responsibilitiesTitle: 'लोक सूचना अधिकारी के कर्तव्य और जिम्मेदारियां',
      responsibilitiesSubtitle: 'नागरिकों से सूचना आवेदन मिलने के पहले 5 दिनों में लोक सूचना अधिकारी द्वारा की जाने वाली कार्रवाई',
      readMore: 'और पढ़ें',
      showLess: 'कम दिखाएं',
    },
    feed: {
      uploadTitle: 'न्यूज़ पोस्ट',
      mediaBoxText: 'वीडियो / फोटो जोड़ें',
      mediaBoxSub: '(गैलरी से चुनें)',
      headlinePlaceholder: 'हेडलाइन लिखें',
      captionPlaceholder: 'अपनी RTI कहानी विस्तार से लिखें...',
      categoryLabel: 'श्रेणी:',
      cancel: 'रद्द करें',
      post: 'पोस्ट करें',
      commentsTitle: 'टिप्पणियाँ',
      noComments: 'पहली टिप्पणी करें!',
      commentPlaceholder: 'टिप्पणी लिखें...',
      close: 'बंद करें',
      loginAsYou: 'आप',
      viewAllCommentsPrefix: 'सभी',
      viewAllCommentsSuffix: 'टिप्पणियाँ देखें',
      tags: {
        successStory: 'सफल कहानी',
        applicationFiled: 'आवेदन दर्ज',
        victory: 'जीत',
        question: 'प्रश्न',
        officialUpdate: 'आधिकारिक अपडेट',
        corruptionExposed: 'भ्रष्टाचार उजागर',
      },
      captionRequiredTitle: 'कैप्शन जरूरी है',
      captionRequiredMessage: 'पोस्ट करने से पहले कुछ लिखें।',
      showLess: 'कम दिखाएं',
      showMore: 'और दिखाएं',
    },
  },
  mr: {
    common: {
      home: 'होम',
      about: 'आमच्याबद्दल',
      feed: 'फीड',
      rti: 'RTI म्हणजे काय',
      laws: 'महत्त्वाचे कायदे',
      contact: 'संपर्क',
      signUp: 'साइन अप',
      profile: 'प्रोफाइल',
      dashboard: 'डॅशबोर्ड',
      logout: 'लॉगआउट',
      login: 'लॉगिन',
      aboutUs: 'आमच्याबद्दल',
      contactUs: 'संपर्क करा',
      trendingNews: 'ट्रेंडिंग बातम्या',
      stateCoverage: 'राज्य कव्हरेज',
      quickLinks: 'क्विक लिंक्स',
      aboutRtiNews: 'RTI News बद्दल',
      followOn: 'RTI अॅप फॉलो करा',
      latestNews: 'ताज्या बातम्या',
      newsByState: 'राज्यानुसार बातम्या',
      news: 'बातम्या',
      politics: 'राजकारण',
      elections: 'निवडणुका',
      viral: 'व्हायरल',
      astrology: 'ज्योतिष',
      horoscopeHindi: 'हिंदी राशिभविष्य',
      horoscopeEnglish: 'इंग्रजी राशिभविष्य',
      latestPoliticalNews: 'ताज्या राजकीय बातम्या',
      like: 'आवडले',
      comment: 'टिप्पणी',
      share: 'शेअर',
      likes: 'लाईक्स',
      views: 'व्ह्यूज',
      comments: 'टिप्पण्या',
      shares: 'शेअर्स',
      viewAll: 'पूर्ण पहा',
      viewPost: 'पोस्ट पहा',
      reporter: 'रिपोर्टर',
      video: 'व्हिडिओ',
    },
  },
  bn: {
    common: {
      home: 'হোম',
      about: 'আমাদের সম্পর্কে',
      feed: 'ফিড',
      rti: 'RTI কী',
      laws: 'গুরুত্বপূর্ণ আইন',
      contact: 'যোগাযোগ',
      signUp: 'সাইন আপ',
      profile: 'প্রোফাইল',
      dashboard: 'ড্যাশবোর্ড',
      logout: 'লগআউট',
      login: 'লগইন',
      aboutUs: 'আমাদের সম্পর্কে',
      contactUs: 'যোগাযোগ করুন',
      trendingNews: 'ট্রেন্ডিং খবর',
      stateCoverage: 'রাজ্য কভারেজ',
      quickLinks: 'কুইক লিঙ্ক',
      aboutRtiNews: 'RTI News সম্পর্কে',
      followOn: 'RTI অ্যাপ ফলো করুন',
      latestNews: 'সর্বশেষ খবর',
      newsByState: 'রাজ্যভিত্তিক সংবাদ',
      news: 'সংবাদ',
      politics: 'রাজনীতি',
      elections: 'নির্বাচন',
      viral: 'ভাইরাল',
      astrology: 'জ্যোতিষ',
      horoscopeHindi: 'হিন্দি রাশিফল',
      horoscopeEnglish: 'ইংরেজি রাশিফল',
      latestPoliticalNews: 'সর্বশেষ রাজনৈতিক সংবাদ',
      like: 'পছন্দ',
      comment: 'মন্তব্য',
      share: 'শেয়ার',
      likes: 'লাইক',
      views: 'ভিউ',
      comments: 'মন্তব্য',
      shares: 'শেয়ার',
      viewAll: 'সব দেখুন',
      viewPost: 'পোস্ট দেখুন',
      reporter: 'রিপোর্টার',
      video: 'ভিডিও',
    },
  },
  gu: {
    common: {
      home: 'હોમ',
      about: 'અમારા વિશે',
      feed: 'ફીડ',
      rti: 'RTI શું છે',
      laws: 'મહત્વપૂર્ણ કાયદા',
      contact: 'સંપર્ક',
      signUp: 'સાઇન અપ',
      profile: 'પ્રોફાઇલ',
      dashboard: 'ડેશબોર્ડ',
      logout: 'લોગઆઉટ',
      login: 'લોગિન',
      aboutUs: 'અમારા વિશે',
      contactUs: 'સંપર્ક કરો',
      trendingNews: 'ટ્રેન્ડિંગ સમાચાર',
      stateCoverage: 'રાજ્ય કવરેજ',
      quickLinks: 'ક્વિક લિંક્સ',
      aboutRtiNews: 'RTI News વિશે',
      followOn: 'RTI એપ ફોલો કરો',
      latestNews: 'તાજા સમાચાર',
      newsByState: 'રાજ્યવાર સમાચાર',
      news: 'સમાચાર',
      politics: 'રાજકારણ',
      elections: 'ચૂંટણી',
      viral: 'વાયરલ',
      astrology: 'જ્યોતિષ',
      horoscopeHindi: 'હિન્દી રાશિફળ',
      horoscopeEnglish: 'અંગ્રેજી રાશિફળ',
      latestPoliticalNews: 'તાજા રાજકીય સમાચાર',
      like: 'પસંદ',
      comment: 'ટિપ્પણી',
      share: 'શેર',
      likes: 'લાઇક્સ',
      views: 'વ્યૂઝ',
      comments: 'ટિપ્પણીઓ',
      shares: 'શેર',
      viewAll: 'બધું જુઓ',
      viewPost: 'પોસ્ટ જુઓ',
      reporter: 'રિપોર્ટર',
      video: 'વિડિયો',
    },
  },
  ta: {
    common: {
      home: 'முகப்பு',
      about: 'எங்களை பற்றி',
      feed: 'பீட்',
      rti: 'RTI என்றால் என்ன',
      laws: 'முக்கிய சட்டங்கள்',
      contact: 'தொடர்பு',
      signUp: 'பதிவு செய்யவும்',
      profile: 'சுயவிவரம்',
      dashboard: 'டாஷ்போர்டு',
      logout: 'வெளியேறு',
      login: 'உள்நுழை',
      aboutUs: 'எங்களை பற்றி',
      contactUs: 'தொடர்பு கொள்ளவும்',
      trendingNews: 'டிரெண்டிங் செய்திகள்',
      stateCoverage: 'மாநில கவரேஜ்',
      quickLinks: 'விரைவு இணைப்புகள்',
      aboutRtiNews: 'RTI News பற்றி',
      followOn: 'RTI செயலியை பின்தொடரவும்',
      latestNews: 'சமீபத்திய செய்திகள்',
      newsByState: 'மாநில வாரியான செய்திகள்',
      news: 'செய்திகள்',
      politics: 'அரசியல்',
      elections: 'தேர்தல்கள்',
      viral: 'வைரல்',
      astrology: 'ஜோதிடம்',
      horoscopeHindi: 'இந்தி ராசிபலன்',
      horoscopeEnglish: 'ஆங்கில ராசிபலன்',
      latestPoliticalNews: 'சமீபத்திய அரசியல் செய்திகள்',
      like: 'விருப்பு',
      comment: 'கருத்து',
      share: 'பகிர்',
      likes: 'லைக்ஸ்',
      views: 'வியூஸ்',
      comments: 'கருத்துகள்',
      shares: 'பகிர்வுகள்',
      viewAll: 'முழுவதும் காண்க',
      viewPost: 'பதிவைக் காண்க',
      reporter: 'நிருபர்',
      video: 'வீடியோ',
    },
  },
  te: {
    common: {
      home: 'హోమ్',
      about: 'మా గురించి',
      feed: 'ఫీడ్',
      rti: 'RTI అంటే ఏమిటి',
      laws: 'ముఖ్యమైన చట్టాలు',
      contact: 'సంప్రదించండి',
      signUp: 'సైన్ అప్',
      profile: 'ప్రొఫైల్',
      dashboard: 'డ్యాష్‌బోర్డ్',
      logout: 'లాగ్ఔట్',
      login: 'లాగిన్',
      aboutUs: 'మా గురించి',
      contactUs: 'సంప్రదించండి',
      trendingNews: 'ట్రెండింగ్ వార్తలు',
      stateCoverage: 'రాష్ట్ర కవరేజ్',
      quickLinks: 'క్విక్ లింక్స్',
      aboutRtiNews: 'RTI News గురించి',
      followOn: 'RTI యాప్‌ను ఫాలో చేయండి',
      latestNews: 'తాజా వార్తలు',
      newsByState: 'రాష్ట్రాల వారీ వార్తలు',
      news: 'వార్తలు',
      politics: 'రాజకీయాలు',
      elections: 'ఎన్నికలు',
      viral: 'వైరల్',
      astrology: 'జ్యోతిష్యం',
      horoscopeHindi: 'హిందీ రాశిఫలం',
      horoscopeEnglish: 'ఇంగ్లీష్ రాశిఫలం',
      latestPoliticalNews: 'తాజా రాజకీయ వార్తలు',
      like: 'లైక్',
      comment: 'వ్యాఖ్య',
      share: 'షేర్',
      likes: 'లైక్స్',
      views: 'వ్యూస్',
      comments: 'వ్యాఖ్యలు',
      shares: 'షేర్లు',
      viewAll: 'మొత్తం చూడండి',
      viewPost: 'పోస్ట్ చూడండి',
      reporter: 'రిపోర్టర్',
      video: 'వీడియో',
    },
  },
  kn: {
    common: {
      home: 'ಮುಖಪುಟ',
      about: 'ನಮ್ಮ ಬಗ್ಗೆ',
      feed: 'ಫೀಡ್',
      rti: 'RTI ಎಂದರೇನು',
      laws: 'ಮುಖ್ಯ ಕಾನೂನುಗಳು',
      contact: 'ಸಂಪರ್ಕ',
      signUp: 'ಸೈನ್ ಅಪ್',
      profile: 'ಪ್ರೊಫೈಲ್',
      dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      logout: 'ಲಾಗ್‌ಔಟ್',
      login: 'ಲಾಗಿನ್',
      aboutUs: 'ನಮ್ಮ ಬಗ್ಗೆ',
      contactUs: 'ಸಂಪರ್ಕಿಸಿ',
      trendingNews: 'ಟ್ರೆಂಡಿಂಗ್ ಸುದ್ದಿ',
      stateCoverage: 'ರಾಜ್ಯ ಕವರೆಜ್',
      quickLinks: 'ಕ್ವಿಕ್ ಲಿಂಕ್ಸ್',
      aboutRtiNews: 'RTI News ಬಗ್ಗೆ',
      followOn: 'RTI ಆಪ್ ಅನ್ನು ಫಾಲೋ ಮಾಡಿ',
      latestNews: 'ತಾಜಾ ಸುದ್ದಿ',
      newsByState: 'ರಾಜ್ಯವಾರ ಸುದ್ದಿ',
      news: 'ಸುದ್ದಿ',
      politics: 'ರಾಜಕೀಯ',
      elections: 'ಚುನಾವಣೆಗಳು',
      viral: 'ವೈರಲ್',
      astrology: 'ಜ್ಯೋತಿಷ್ಯ',
      horoscopeHindi: 'ಹಿಂದಿ ರಾಶಿಭವಿಷ್ಯ',
      horoscopeEnglish: 'ಇಂಗ್ಲಿಷ್ ರಾಶಿಭವಿಷ್ಯ',
      latestPoliticalNews: 'ತಾಜಾ ರಾಜಕೀಯ ಸುದ್ದಿ',
      like: 'ಇಷ್ಟ',
      comment: 'ಪ್ರತಿಕ್ರಿಯೆ',
      share: 'ಹಂಚಿಕೊಳ್ಳಿ',
      likes: 'ಲೈಕ್ಸ್',
      views: 'ವೀಕ್ಷಣೆಗಳು',
      comments: 'ಕಾಮೆಂಟ್‌ಗಳು',
      shares: 'ಹಂಚಿಕೆಗಳು',
      viewAll: 'ಪೂರ್ಣವಾಗಿ ನೋಡಿ',
      viewPost: 'ಪೋಸ್ಟ್ ನೋಡಿ',
      reporter: 'ವರದಿಗಾರ',
      video: 'ವೀಡಿಯೊ',
    },
  },
  ml: {
    common: {
      home: 'ഹോം',
      about: 'ഞങ്ങളേക്കുറിച്ച്',
      feed: 'ഫീഡ്',
      rti: 'RTI എന്താണ്',
      laws: 'പ്രധാന നിയമങ്ങൾ',
      contact: 'ബന്ധപ്പെടുക',
      signUp: 'സൈൻ അപ്പ്',
      profile: 'പ്രൊഫൈൽ',
      dashboard: 'ഡാഷ്ബോർഡ്',
      logout: 'ലോഗ്ഔട്ട്',
      login: 'ലോഗിൻ',
      aboutUs: 'ഞങ്ങളേക്കുറിച്ച്',
      contactUs: 'ബന്ധപ്പെടുക',
      trendingNews: 'ട്രെൻഡിംഗ് വാർത്തകൾ',
      stateCoverage: 'സംസ്ഥാന കവറേജ്',
      quickLinks: 'ക്വിക് ലിങ്കുകൾ',
      aboutRtiNews: 'RTI Newsയെക്കുറിച്ച്',
      followOn: 'RTI ആപ്പ് പിന്തുടരുക',
      latestNews: 'പുതിയ വാർത്തകൾ',
      newsByState: 'സംസ്ഥാന വാർത്തകൾ',
      news: 'വാർത്തകൾ',
      politics: 'രാഷ്ട്രീയം',
      elections: 'തിരഞ്ഞെടുപ്പുകൾ',
      viral: 'വൈറൽ',
      astrology: 'ജ്യോതിഷം',
      horoscopeHindi: 'ഹിന്ദി രാശിഫലം',
      horoscopeEnglish: 'ഇംഗ്ലീഷ് രാശിഫലം',
      latestPoliticalNews: 'പുതിയ രാഷ്ട്രീയ വാർത്തകൾ',
      like: 'ലൈക്ക്',
      comment: 'അഭിപ്രായം',
      share: 'ഷെയർ',
      likes: 'ലൈക്കുകൾ',
      views: 'വ്യൂസ്',
      comments: 'അഭിപ്രായങ്ങൾ',
      shares: 'ഷെയറുകൾ',
      viewAll: 'മുഴുവൻ കാണുക',
      viewPost: 'പോസ്റ്റ് കാണുക',
      reporter: 'റിപ്പോർട്ടർ',
      video: 'വീഡിയോ',
    },
  },
  pa: {
    common: {
      home: 'ਘਰ',
      about: 'ਸਾਡੇ ਬਾਰੇ',
      feed: 'ਫੀਡ',
      rti: 'RTI ਕੀ ਹੈ',
      laws: 'ਮਹੱਤਵਪੂਰਨ ਕਾਨੂੰਨ',
      contact: 'ਸੰਪਰਕ',
      signUp: 'ਸਾਇਨ ਅੱਪ',
      profile: 'ਪ੍ਰੋਫਾਈਲ',
      dashboard: 'ਡੈਸ਼ਬੋਰਡ',
      logout: 'ਲੌਗਆਉਟ',
      login: 'ਲੌਗਇਨ',
      aboutUs: 'ਸਾਡੇ ਬਾਰੇ',
      contactUs: 'ਸੰਪਰਕ ਕਰੋ',
      trendingNews: 'ਟ੍ਰੈਂਡਿੰਗ ਖ਼ਬਰਾਂ',
      stateCoverage: 'ਰਾਜ ਕਵਰੇਜ',
      quickLinks: 'ਕੁਇਕ ਲਿੰਕਸ',
      aboutRtiNews: 'RTI News ਬਾਰੇ',
      followOn: 'RTI ਐਪ ਫਾਲੋ ਕਰੋ',
      latestNews: 'ਤਾਜ਼ਾ ਖ਼ਬਰਾਂ',
      newsByState: 'ਰਾਜਵਾਰ ਖ਼ਬਰਾਂ',
      news: 'ਖ਼ਬਰਾਂ',
      politics: 'ਰਾਜਨੀਤੀ',
      elections: 'ਚੋਣਾਂ',
      viral: 'ਵਾਇਰਲ',
      astrology: 'ਜੋਤਿਸ਼',
      horoscopeHindi: 'ਹਿੰਦੀ ਰਾਸ਼ਿਫਲ',
      horoscopeEnglish: 'ਅੰਗਰੇਜ਼ੀ ਰਾਸ਼ਿਫਲ',
      latestPoliticalNews: 'ਤਾਜ਼ਾ ਰਾਜਨੀਤਿਕ ਖ਼ਬਰਾਂ',
      like: 'ਪਸੰਦ',
      comment: 'ਟਿੱਪਣੀ',
      share: 'ਸ਼ੇਅਰ',
      likes: 'ਲਾਈਕਸ',
      views: 'ਵਿਊਜ਼',
      comments: 'ਟਿੱਪਣੀਆਂ',
      shares: 'ਸ਼ੇਅਰ',
      viewAll: 'ਸਾਰਾ ਵੇਖੋ',
      viewPost: 'ਪੋਸਟ ਵੇਖੋ',
      reporter: 'ਰਿਪੋਰਟਰ',
      video: 'ਵੀਡੀਓ',
    },
  },
};

function isPlainObject(value) {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
}

function deepMerge(baseValue, overrideValue) {
  if (Array.isArray(overrideValue)) {
    return [...overrideValue];
  }

  if (!isPlainObject(baseValue) || !isPlainObject(overrideValue)) {
    return overrideValue ?? baseValue;
  }

  const mergedValue = { ...baseValue };
  Object.keys(overrideValue).forEach((key) => {
    mergedValue[key] = deepMerge(baseValue[key], overrideValue[key]);
  });
  return mergedValue;
}

export function getSiteCopy(language) {
  const baseCopy = SITE_COPY.en;
  if (!language || language === 'en' || !SITE_COPY[language]) {
    return baseCopy;
  }
  return deepMerge(baseCopy, SITE_COPY[language]);
}
