import { StyleSheet } from 'react-native';

const AddNewsStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#f8fafc' },
  scrollView: { flex: 1 },
  scrollContent: { padding: 16, paddingBottom: 110 },

  heroCard: {
    backgroundColor: '#ffffff',
    borderRadius: 22,
    padding: 20,
    marginBottom: 14,
    elevation: 3,
  },
  heroEyebrow: {
    fontSize: 11,
    color: '#7c3aed',
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 4,
  },
  heroTitle: { fontSize: 22, fontWeight: '800', color: '#0f172a', marginBottom: 4 },
  heroSubtitle: { fontSize: 12, color: '#64748b' },

  card: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 16,
    marginBottom: 14,
    elevation: 3,
  },

  fieldLabel: { fontSize: 13, fontWeight: '800', color: '#0f172a', marginBottom: 6 },
  fieldHint: { fontSize: 11, color: '#94a3b8', marginBottom: 8 },
  required: { color: '#dc2626' },
  fieldHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  moreToggleText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#2563eb',
  },

  inputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: '#f8fafc',
    marginBottom: 4,
  },
  input: {
    flex: 1,
    fontSize: 14,
    color: '#0f172a',
    paddingVertical: 0,
  },
  inputExpanded: {
    minHeight: 70,
    textAlignVertical: 'top',
  },

  richToolbar: {
    backgroundColor: '#f1f5f9',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderBottomWidth: 0,
    height: 44,
  },
  richEditor: {
    minHeight: 160,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    backgroundColor: '#ffffff',
    overflow: 'hidden',
    marginBottom: 4,
  },
  richEditorExpanded: {
    minHeight: 220,
  },
  richEditorInner: {
    backgroundColor: '#ffffff',
    color: '#0f172a',
    fontSize: 14,
    placeholderColor: '#94a3b8',
    contentCSSText: 'font-family: sans-serif; padding: 8px; line-height: 1.6;',
  },
  webTextInput: {
    minHeight: 160,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    backgroundColor: '#ffffff',
    padding: 12,
    fontSize: 14,
    color: '#0f172a',
    textAlignVertical: 'top',
  },

  stateSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 13,
    backgroundColor: '#f8fafc',
  },
  stateSelectorText: {
    flex: 1,
    fontSize: 14,
    color: '#0f172a',
    fontWeight: '500',
  },
  locationLockCard: {
    borderWidth: 1,
    borderColor: '#e0f2fe',
    backgroundColor: '#f0f9ff',
    borderRadius: 14,
    padding: 14,
    marginBottom: 6,
  },
  locationLockHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  locationLockTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#0f172a',
  },
  locationLockSubtitle: {
    marginTop: 2,
    fontSize: 11,
    color: '#64748b',
  },
  locationLockBadge: {
    backgroundColor: '#2563eb',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  locationLockBadgeText: {
    fontSize: 9,
    letterSpacing: 0.6,
    fontWeight: '800',
    color: '#ffffff',
  },
  locationLockText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0f172a',
  },

  mediaToggleRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
    marginTop: 6,
  },
  mediaToggleBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    backgroundColor: '#f8fafc',
  },
  mediaToggleBtnActive: { borderColor: '#7c3aed', backgroundColor: '#ede9fe' },
  mediaToggleBtnText: { fontSize: 12, fontWeight: '700', color: '#64748b' },
  mediaToggleBtnTextActive: { color: '#7c3aed' },

  mediaSection: { marginBottom: 14 },
  mediaPickBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1.5,
    borderColor: '#2563eb',
    borderStyle: 'dashed',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#eff6ff',
  },
  mediaPickBtnText: { fontSize: 13, fontWeight: '700', color: '#2563eb' },
  mediaPickBtnDisabled: {
    borderColor: '#cbd5e1',
    backgroundColor: '#f8fafc',
  },
  mediaPickBtnTextDisabled: {
    color: '#94a3b8',
  },
  videoPickBtn: {
    borderColor: '#7c3aed',
    backgroundColor: '#faf5ff',
  },
  videoPickBtnText: {
    color: '#7c3aed',
  },
  filePickBtn: {
    borderColor: '#0f766e',
    backgroundColor: '#f0fdfa',
  },
  filePickBtnText: {
    color: '#0f766e',
  },
  fileInfoRow: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: '#f0fdfa',
    borderWidth: 1,
    borderColor: '#99f6e4',
  },
  fileInfoText: {
    flex: 1,
    fontSize: 12,
    fontWeight: '700',
    color: '#0f766e',
  },
  fileRemoveBtn: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0f766e',
  },
  mediaStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    gap: 8,
  },
  mediaStatusText: {
    fontSize: 12,
    color: '#16a34a',
    fontWeight: '700',
    flex: 1,
  },

  videoPreviewWrap: {
    marginTop: 10,
    borderRadius: 12,
    overflow: 'hidden',
    position: 'relative',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  videoPreview: {
    width: '100%',
    height: 190,
    backgroundColor: '#0f172a',
  },
  videoRemoveBtn: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: 'rgba(15,23,42,0.7)',
    alignItems: 'center',
    justifyContent: 'center',
  },

  thumbContainer: { position: 'relative', marginRight: 8 },
  thumb: { width: 80, height: 80, borderRadius: 10 },
  thumbRemoveBtn: {
    position: 'absolute',
    top: 4,
    right: 4,
    backgroundColor: '#dc2626',
    borderRadius: 999,
    width: 18,
    height: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },

  adminNoteBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: '#fefce8',
    borderWidth: 1,
    borderColor: '#fde68a',
    borderRadius: 10,
    padding: 12,
    marginTop: 8,
    marginBottom: 14,
  },
  adminNoteText: { flex: 1, fontSize: 12, color: '#92400e', fontWeight: '600', lineHeight: 18 },

  submitBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: '#7c3aed',
    borderRadius: 14,
    paddingVertical: 14,
    marginTop: 6,
    elevation: 4,
  },
  submitBtnText: { fontSize: 15, fontWeight: '800', color: '#ffffff' },

  stateModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  stateModalBox: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    maxHeight: '75%',
  },
  stateModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  stateModalTitle: { fontSize: 17, fontWeight: '800', color: '#0f172a' },

  stateSearchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 12,
    backgroundColor: '#f8fafc',
  },
  stateSearchInput: { flex: 1, fontSize: 13, color: '#0f172a' },

  stateItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 13,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  stateItemActive: { backgroundColor: '#f5f3ff' },
  stateItemText: { fontSize: 14, color: '#334155', fontWeight: '500' },
  stateItemTextActive: { color: '#7c3aed', fontWeight: '700' },
});

export default AddNewsStyles;
