import { StyleSheet } from 'react-native';

const AppointmentLetterStyles = StyleSheet.create({
  // ✅ UPDATED: borderRadius 0 - sharp corners
  apptCard:         {
    borderRadius: 0,
    overflow: 'hidden',
    marginBottom: 4,
    elevation: 6,
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    backgroundColor: '#e9edf0',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
  },
  apptPressBadge:   { alignItems:'center', paddingTop:10 },
  apptPressBadgeText:{ fontSize:10, fontWeight:'800', color:'#fff', backgroundColor:'#dc2626', paddingHorizontal:14, paddingVertical:3, borderRadius:999, letterSpacing:2, overflow:'hidden' },
  apptLogoRow:      { flexDirection:'row', alignItems:'center', justifyContent:'space-between', padding:12, paddingBottom:4, gap:8 },
  apptBrandLeft:    { flex:1 },
  apptBrandTitle:   { fontSize:20, fontWeight:'900', lineHeight:22 },
  apptBrandBha:     { color:'#f97316' },
  apptBrandRti:     { color:'#1d4ed8' },
  apptBranya:       { color:'#15803d' },
  apptBrandVoice:   { fontSize:20, fontWeight:'900', lineHeight:35, color:'#111827' },
  apptBrandEmoji:   { color:'#f97316' },
  apptRNI:          { fontSize:9, color:'#dc2626', marginTop:1, fontWeight:'900' },
  apptCenterLogo:   { width:60, height:60, borderRadius:30, backgroundColor:'#e9edf0', borderWidth:2, borderColor:'#15803d', alignItems:'center', justifyContent:'center' },
  apptCenterLogoText:{ fontSize:8, fontWeight:'800', color:'#15803d', textAlign:'center', lineHeight:11 },
  apptCertLogo:     { width:76, height:76, borderRadius:38, borderWidth:2.5, borderColor:'#1a5c2a' },

  // ✅ UPDATED: height kam, sides bade
  apptNetworkBadge: { backgroundColor:'#1d4ed8', borderRadius:4, paddingHorizontal:10, paddingVertical:3, alignItems:'center' },
  apptNetworkText:  { fontSize:9, fontWeight:'700', color:'#fff', textAlign:'center', lineHeight:13 },
  apptNetworkRight: { flex:1, alignItems:'flex-end' },

  apptRedBanner:    { backgroundColor:'#dc2626', marginTop:0, paddingVertical:8, paddingHorizontal:20, marginHorizontal:12, borderRadius:0 },
  apptRedBannerText:{ fontSize:25, fontWeight:'900', color:'#fff', textAlign:'center' },
  apptSubtitle:     { fontSize:11, fontWeight:'600', color:'#374151', textAlign:'center', paddingHorizontal:16, paddingTop:8, backgroundColor:'#e9edf0', lineHeight:16 },
  apptRibbonRow:    { marginHorizontal:12, marginTop:12, marginBottom:8, flexDirection:'row', alignItems:'center', justifyContent:'flex-start', gap:8, backgroundColor:'#e9edf0' },
  apptRibbonImage:  { width:'75%', height:44, resizeMode:'contain', backgroundColor:'#e9edf0' },
  apptRibbonLogo:   { width:44, height:44, resizeMode:'contain', backgroundColor:'#e9edf0' },
  apptSince:        { fontSize:11, color:'#374151', lineHeight:17, paddingHorizontal:14, paddingBottom:8, backgroundColor:'#e9edf0' },
  apptSinceHighlight:{ color:'#dc2626', fontWeight:'800' },
  apptDetailsRow:   { flexDirection:'row', alignItems:'flex-start', padding:12, backgroundColor:'#e9edf0', gap:10 },
  apptDetailsLeft:  { flex:1 },
  apptDetailLine:   { fontSize:12, color:'#374151', marginBottom:5, lineHeight:18 },
  apptDetailBold:   { fontWeight:'700', color:'#111827' },
  apptDetailName:   { color:'#dc2626', fontWeight:'900', fontSize:16 },
  apptDetailRed:    { color:'#dc2626', fontWeight:'600' },
  apptDate:         { fontSize:13, fontWeight:'700', color:'#111827', marginBottom:8 },
  apptDateRed:      { color:'#dc2626' },
  apptBody:         { fontSize:11, color:'#4b5563', lineHeight:17 },
  apptBodyBold:     { fontWeight:'700' },
  apptPhotoBox:     { width:80, height:96, borderWidth:2, borderColor:'#d1d5db', borderRadius:8, overflow:'hidden', backgroundColor:'#e9edf0' },
  apptPhoto:        { width:'100%', height:'100%' },
  apptSignRow:      { flexDirection:'row', justifyContent:'space-between', alignItems:'flex-end', padding:12, backgroundColor:'#e9edf0' },
  apptSignRight:    { alignItems:'flex-end' },
  apptContact:      { fontSize:11, fontWeight:'700', color:'#374151' },
  apptContactNum:   { fontSize:12, fontWeight:'800', color:'#111827' },
  apptFaithfully:   { fontSize:11, color:'#374151', marginBottom:2 },
  apptSignName:     { fontSize:11, fontWeight:'600', color:'#111827' },
  apptSignSub:      { fontSize:10, color:'#6b7280' },
  apptFooter:       { backgroundColor:'#dc2626', paddingVertical:8, paddingHorizontal:20, alignItems:'center', marginHorizontal:12, borderRadius:0, marginBottom:8 },
  apptFooterText:   { fontSize:10, color:'#fff', fontWeight:'600', textAlign:'center' },
  apptTemplate:     { width:'100%', aspectRatio: 210 / 297 },
  apptImage:        { resizeMode:'cover' },
  apptOverlay:      { ...StyleSheet.absoluteFillObject },
  apptNameValue:    { position:'absolute', top:'55%', left:'24%', right:'10%', fontSize:12, fontWeight:'700', color:'#1e3a8a' },
  apptDesigValue:   { position:'absolute', top:'59%', left:'28%', right:'10%', fontSize:11, fontWeight:'600', color:'#1e40af' },
  apptLocationValue:{ position:'absolute', top:'63%', left:'36%', right:'10%', fontSize:10.5, fontWeight:'600', color:'#1e40af' },
  apptDateFromValue:{ position:'absolute', top:'67%', left:'24%', fontSize:10.5, fontWeight:'600', color:'#1e40af' },
  apptDateToValue:  { position:'absolute', top:'67%', left:'40%', fontSize:10.5, fontWeight:'600', color:'#1e40af' },
  apptPhotoFrame:   { position:'absolute', top:'61%', right:'14%', width:'18%', aspectRatio: 3 / 4, borderWidth:1, borderColor:'#e9edf0', backgroundColor:'#f8fafc', overflow:'hidden' },
});

export default AppointmentLetterStyles;
