import { StyleSheet } from 'react-native';

const C = {
  orange:       '#F97316',
  orangeLight:  '#FFF7ED',
  orangeMid:    '#FDBA74',
  white:        '#FFFFFF',
  pageBg:       '#F3F4F6',
  surface:      '#F9FAFB',
  textDark:     '#111111',
  textMid:      '#555555',
  textMuted:    '#9CA3AF',
  border:       '#E5E7EB',
  green:        '#16a34a',
  greenLight:   '#F0FDF4',
  greenMid:     '#86EFAC',
  red:          '#DC2626',
  redLight:     '#FEF2F2',
  redMid:       '#FCA5A5',
};

const CertificationStyles = StyleSheet.create({

  root: {
    flex: 1,
    backgroundColor: C.pageBg,
  },

  backRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 14,
    backgroundColor: C.white,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  backText: {
    color: C.orange,
    fontSize: 14,
    fontWeight: '500',
  },

  scrollView:    { flex: 1, backgroundColor: C.pageBg },
  scrollContent: {
  flexGrow: 1,
  paddingVertical: 20,
  paddingHorizontal: 32,
  paddingBottom: 110,
  backgroundColor: C.pageBg,
  alignItems: 'center',
},

  metricsRow: {
  width: '100%',
  maxWidth: 900,
  width: '100%',
  maxWidth: 1100,
  backgroundColor: C.orange,
  borderRadius: 18,
  paddingVertical: 22,
  paddingHorizontal: 24,
  marginBottom: 16,
},
  heroEyebrow: {
    fontSize: 11,
    color: '#FED7AA',
    fontWeight: '500',
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    marginBottom: 6,
  },
  heroTitle: {
    fontSize: 26,
    fontWeight: '600',
    color: C.white,
    lineHeight: 32,
  },

  metricsRow: {
  width: '100%',
  maxWidth: 1100,
  flexDirection: 'row',
  gap: 12,
  marginBottom: 16,
},
  metricCard: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: 18,
    paddingHorizontal: 10,
    alignItems: 'center',
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.border,
  },
  metricPrimary:   { borderTopWidth: 3, borderTopColor: C.orange },
  metricSecondary: { borderTopWidth: 3, borderTopColor: C.green },
  metricAccent:    { borderTopWidth: 3, borderTopColor: C.orangeMid },
  metricValue: {
    fontSize: 26,
    fontWeight: '600',
    color: C.textDark,
    marginBottom: 4,
  },
  metricLabel: {
    fontSize: 11,
    fontWeight: '500',
    color: C.textMuted,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    textAlign: 'center',
  },

  card: {
  width: '100%',
  maxWidth: 1100,
  backgroundColor: C.white,
  borderRadius: 18,
  padding: 20,
  marginBottom: 16,
  borderWidth: 1,
  borderColor: C.border,
},
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: C.textDark,
    marginBottom: 14,
  },

  certCard: {
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 14,
    padding: 16,
    marginBottom: 12,
    backgroundColor: C.white,
  },
  certTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  certTitle: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: C.textDark,
    lineHeight: 22,
  },

  resultBadge: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 999,
  },
  passBadge:       { backgroundColor: C.greenLight, borderWidth: 1, borderColor: C.greenMid },
  retryBadge:      { backgroundColor: C.redLight,   borderWidth: 1, borderColor: C.redMid   },
  resultBadgeText: { fontSize: 12, fontWeight: '600' },
  passText:        { color: C.green },
  failText:        { color: C.red   },

  pendingBadge: {
    backgroundColor: C.orangeLight,
    borderWidth: 1,
    borderColor: C.orangeMid,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 999,
  },
  pendingBadgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: C.orange,
  },

  scoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 10,
  },
  scoreText: { fontSize: 13, color: C.textMid },
  scoreBold: { fontWeight: '600', color: C.textDark },

  certFileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 12,
    backgroundColor: C.greenLight,
    alignSelf: 'flex-start',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: C.greenMid,
  },
  certFileText: { fontSize: 12, color: C.green, fontWeight: '500' },

  actionRow: { flexDirection: 'row', gap: 8, marginTop: 4 },
  actionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: C.orangeLight,
    borderWidth: 1,
    borderColor: C.orangeMid,
  },
  actionBtnGreen: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: C.greenLight,
    borderWidth: 1,
    borderColor: C.greenMid,
  },
  actionBtnDisabled: {
    backgroundColor: C.surface,
    borderColor: C.border,
  },
  actionBtnText:         { fontSize: 12, fontWeight: '600', color: C.orange },
  actionBtnTextGreen:    { fontSize: 12, fontWeight: '600', color: C.green },
  actionBtnTextDisabled: { fontSize: 12, fontWeight: '600', color: C.textMuted },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: C.white,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 24,
    paddingBottom: 40,
    maxHeight: '90%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: { fontSize: 17, fontWeight: '600', color: C.textDark },

  quizProgress: {
    fontSize: 12,
    fontWeight: '500',
    color: C.textMuted,
    marginBottom: 8,
  },
  progressBarWrap: {
    height: 5,
    backgroundColor: C.border,
    borderRadius: 999,
    marginBottom: 20,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: C.orange,
    borderRadius: 999,
  },
  questionText: {
    fontSize: 15,
    fontWeight: '600',
    color: C.textDark,
    lineHeight: 23,
    marginBottom: 16,
  },
  optionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.surface,
    marginBottom: 10,
  },
  optionBtnSelected: {
    borderColor: C.orange,
    backgroundColor: C.orangeLight,
  },
  optionLabel: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: C.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  optionLabelSelected:     { backgroundColor: C.orange },
  optionLabelText:         { fontSize: 13, fontWeight: '600', color: C.textMid },
  optionLabelTextSelected: { color: C.white },
  optionText:              { flex: 1, fontSize: 14, color: C.textMid, fontWeight: '500' },
  optionTextSelected:      { color: C.orange, fontWeight: '600' },
  nextBtn: {
    marginTop: 8,
    backgroundColor: C.orange,
    borderRadius: 12,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  nextBtnDisabled: { opacity: 0.45 },
  nextBtnText:     { fontSize: 15, fontWeight: '600', color: C.white },

  resultCenterWrap: { alignItems: 'center', marginBottom: 20 },
  resultBigBadge: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 20,
    paddingHorizontal: 32,
    borderRadius: 20,
  },
  resultBigText: { fontSize: 20, fontWeight: '600' },
  resultInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  resultInfoLabel: { fontSize: 13, color: C.textMuted, fontWeight: '500' },
  resultInfoValue: {
    fontSize: 14,
    fontWeight: '600',
    color: C.textDark,
    maxWidth: '60%',
    textAlign: 'right',
  },
  downloadBtn: {
    marginTop: 20,
    backgroundColor: C.green,
    borderRadius: 12,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  downloadBtnText: { fontSize: 15, fontWeight: '600', color: C.white },

  loadingText: { fontSize: 13, color: C.textMuted, textAlign: 'center', paddingVertical: 12 },
  emptyText:   { fontSize: 13, color: C.textMuted, textAlign: 'center', paddingVertical: 16 },
});

export default CertificationStyles;