import { StyleSheet, Platform, StatusBar } from 'react-native';

const NewsFeedStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
  padding: 16,
  paddingBottom: 96,
  ...(Platform.OS === 'web' ? {
    maxWidth: 900,
    width: '100%',
    alignSelf: 'center',
    paddingHorizontal: 32,
  } : {}),
},

  // ─── Custom Header Styles ─────────────────────────────────────────
  customHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 24) + 10 : 54,
    paddingBottom: 14,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#FFE0CC',
    elevation: 3,
    shadowColor: '#FF6600',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
  },
customHeaderWeb: {
  alignItems: 'center',
},
headerInner: {
  width: '100%',
  maxWidth: 900,
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
  paddingHorizontal: 32,
},


  backButton: {
    padding: 8,
    borderRadius: 10,
    backgroundColor: '#fff0f5',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0f172a',
    letterSpacing: 0.2,
  },
  headerAddButton: {
    padding: 8,
    borderRadius: 10,
    backgroundColor: '#fff0f5',
  },

  // ─── Edit/Delete Button Row ───────────────────────────────────────
  editDeleteRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#fff0f5',
    gap: 12,
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: '#fff0f5',
    borderRadius: 8,
    gap: 6,
  },
  editButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FF6600',
  },
  deleteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: '#fef2f2',
    borderRadius: 8,
    gap: 6,
  },
  deleteButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#ef4444',
  },

  // ─── Edit Modal Input Styles ──────────────────────────────────────
  editInput: {
    borderWidth: 1,
    borderColor: '#ffe4ef',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 11,
    fontSize: 14,
    color: '#0f172a',
    marginBottom: 12,
    backgroundColor: '#fffafc',
  },

  // ─── Hero Card ────────────────────────────────────────────────────
  heroCard: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#ffe4ef',
    borderRadius: 20,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#FF6600',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.07,
    shadowRadius: 14,
    elevation: 3,
  },
  heroEyebrow: {
    fontSize: 11,
    color: '#FF6600',
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 6,
  },
  heroTitle: {
    fontSize: 24,
    lineHeight: 32,
    color: '#0f172a',
    fontWeight: '800',
    marginBottom: 6,
  },
  heroSubtitle: {
    fontSize: 13,
    lineHeight: 21,
    color: '#64748b',
  },
  addNewsButton: {
    marginTop: 16,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FF6600',
    borderRadius: 14,
    paddingVertical: 11,
    paddingHorizontal: 18,
  },
  addNewsButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#ffffff',
  },
  ownerRow: {
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  ownerBadge: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#fff0f5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ownerInfo: {
    flex: 1,
  },
  ownerName: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0f172a',
  },
  ownerEmail: {
    marginTop: 3,
    fontSize: 12,
    color: '#64748b',
  },

  // ─── Metrics ──────────────────────────────────────────────────────
  metricsRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  metricCard: {
  flex: 1,
  borderRadius: 16,
  paddingVertical: 18,
  paddingHorizontal: 16,
  backgroundColor: '#ffffff',
  borderWidth: 1,
  borderColor: '#FFE0CC',
  borderTopWidth: 3,
  borderTopColor: '#FF6600',
},
metricPrimary: {
  borderTopColor: '#FF6600',
},
metricSecondary: {
  borderTopColor: '#FF6600',
},
metricAccent: {
  borderTopColor: '#FF6600',
},
metricTopRow: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
  marginBottom: 14,
},
metricIconCircle: {
  width: 36,
  height: 36,
  borderRadius: 18,
  backgroundColor: '#fff5ee',
  alignItems: 'center',
  justifyContent: 'center',
},
metricBadge: {
  paddingHorizontal: 10,
  paddingVertical: 4,
  borderRadius: 20,
  backgroundColor: '#fff5ee',
  borderWidth: 1,
  borderColor: '#FFE0CC',
},
metricBadgeText: {
  fontSize: 11,
  color: '#FF6600',
  fontWeight: '600',
},
metricValue: {
  fontSize: 28,
  fontWeight: '800',
  color: '#0f172a',
  marginBottom: 4,
},
metricLabel: {
  fontSize: 12,
  fontWeight: '600',
  color: '#64748b',
},
  // ─── Section Card ─────────────────────────────────────────────────
  card: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#ffe4ef',
    borderRadius: 18,
    padding: 18,
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 17,
    color: '#0f172a',
    fontWeight: '700',
    marginBottom: 4,
  },
  sectionText: {
    fontSize: 13,
    lineHeight: 20,
    color: '#94a3b8',
    marginBottom: 14,
  },
  // ─── News Card ────────────────────────────────────────────────────
  newsCard: {
    borderWidth: 1,
    borderColor: '#ffe4ef',
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    backgroundColor: '#ffffff',
    shadowColor: '#FF6600',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  newsTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    marginBottom: 10,
  },
  authorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  authorAvatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#ffe4ef',
  },
  authorAvatarBtn: {
    borderRadius: 12,
  },
  authorMetaDot: {
    fontSize: 12,
    color: '#F9C8A8',
    fontWeight: '800',
    marginHorizontal: 2,
  },
  authorSeat: {
    fontSize: 12,
    color: '#64748b',
    fontWeight: '600',
    maxWidth: 170,
  },
  authorLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#94a3b8',
  },
  authorName: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0f172a',
  },
  authorBadge: {
    marginLeft: 2,
  },
  categoryBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: '#fff0f5',
    borderWidth: 1,
    borderColor: '#ffe4ef',
  },
  categoryBadgeText: {
    color: '#FF6600',
    fontSize: 11,
    fontWeight: '700',
  },
  newsDate: {
    fontSize: 11,
    color: '#94a3b8',
  },
  newsTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#0f172a',
    marginBottom: 6,
    lineHeight: 24,
  },
  newsSubtitle: {
    fontSize: 13,
    color: '#475569',
    fontWeight: '600',
    marginBottom: 6,
  },
  newsDescriptionWrap: {
    marginBottom: 8,
  },
  newsDescription: {
    fontSize: 13,
    lineHeight: 20,
    color: '#64748b',
    marginBottom: 6,
  },
  moreBtn: {
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: '#fff0f5',
    borderWidth: 1,
    borderColor: '#ffe4ef',
  },
  moreBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FF6600',
  },
  reportDetailsBox: {
    marginTop: 10,
    padding: 12,
    borderRadius: 12,
    backgroundColor: '#fffafc',
    borderWidth: 1,
    borderColor: '#ffe4ef',
  },
  reportDetailsTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: '#FF6600',
    marginBottom: 6,
  },
  reportDetailLine: {
    fontSize: 12,
    color: '#334155',
    marginBottom: 4,
  },
  reportDetailLabel: {
    fontWeight: '700',
    color: '#64748b',
  },
  reportDetailValue: {
    fontWeight: '600',
    color: '#0f172a',
  },
  detailsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  detailChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#fffafc',
    borderWidth: 1,
    borderColor: '#ffe4ef',
  },
  detailChipText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#334155',
  },
  mediaPreviewWrap: {
    marginBottom: 10,
  },
  mediaInfoBox: {
    marginBottom: 10,
    padding: 12,
    borderRadius: 12,
    backgroundColor: '#fffafc',
    borderWidth: 1,
    borderColor: '#ffe4ef',
  },
  fileInfoBox: {
    marginBottom: 10,
    padding: 12,
    borderRadius: 12,
    backgroundColor: '#fff0f5',
    borderWidth: 1,
    borderColor: '#F9C8A8',
  },
  fileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  fileName: {
    flex: 1,
    fontSize: 12,
    color: '#FF6600',
    fontWeight: '700',
  },
  fileOpenBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#ffe4ef',
  },
  fileOpenText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FF6600',
  },
  videoPreviewWrap: {
    marginBottom: 10,
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#ffe4ef',
    backgroundColor: '#0f172a',
  },
  videoPreview: {
    width: '100%',
    height: 200,
    backgroundColor: '#0f172a',
  },
  mediaLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FF6600',
    marginBottom: 5,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  mediaThumb: {
    width: 92,
    height: 92,
    borderRadius: 12,
    marginRight: 8,
    backgroundColor: '#ffe4ef',
  },
  mediaText: {
    fontSize: 12,
    color: '#94a3b8',
  },

  // ─── Action Row ───────────────────────────────────────────────────
  actionRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  actionIconButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: '#fff0f5',
    borderWidth: 1,
    borderColor: '#ffe4ef',
  },
  actionIconText: {
    color: '#FF6600',
    fontSize: 12,
    fontWeight: '700',
  },
  actionIconButtonActive: {
    backgroundColor: '#FF6600',
    borderColor: '#FF6600',
  },
  actionIconTextActive: {
    fontWeight: '800',
    color: '#ffffff',
  },

  // ─── Comment Modal ────────────────────────────────────────────────
  commentKeyboardAvoider: {
    flex: 1,
  },
  commentOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.4)',
    justifyContent: 'flex-end',
  },
  commentSheet: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 18,
    maxHeight: '75%',
  },
  commentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#ffe4ef',
  },
  commentTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0f172a',
  },
  commentList: {
    flexShrink: 1,
    marginBottom: 12,
  },
  commentItem: {
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ffe4ef',
    backgroundColor: '#fffafc',
    marginBottom: 8,
  },
  commentReplyItem: {
    marginLeft: 18,
    marginTop: 8,
    backgroundColor: '#ffffff',
  },
  commentTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  commentAuthor: {
    fontSize: 12,
    fontWeight: '700',
    color: '#0f172a',
  },
  commentDate: {
    fontSize: 10,
    color: '#94a3b8',
  },
  commentText: {
    fontSize: 12,
    color: '#334155',
    lineHeight: 18,
  },
  commentEditInput: {
    borderWidth: 1,
    borderColor: '#ffe4ef',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 12,
    color: '#0f172a',
    backgroundColor: '#ffffff',
    marginTop: 4,
  },
  commentActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  commentActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: '#fff0f5',
    borderWidth: 1,
    borderColor: '#ffe4ef',
  },
  commentActionBtnActive: {
    backgroundColor: '#FF6600',
    borderColor: '#FF6600',
  },
  commentActionText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FF6600',
  },
  commentActionTextActive: {
    color: '#ffffff',
  },
  commentMiniBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: '#fff0f5',
    borderWidth: 1,
    borderColor: '#ffe4ef',
  },
  commentMiniBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FF6600',
  },
  commentReplyForm: {
    marginTop: 10,
  },
  commentReplyInput: {
    borderWidth: 1,
    borderColor: '#ffe4ef',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 12,
    color: '#0f172a',
    backgroundColor: '#ffffff',
    minHeight: 42,
    maxHeight: 90,
  },
  commentReplyActions: {
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'flex-end',
    marginTop: 8,
  },
  commentRepliesWrap: {
    marginTop: 10,
  },
  commentRepliesToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  commentRepliesLine: {
    width: 24,
    height: 1,
    backgroundColor: '#F9C8A8',
  },
  commentRepliesToggleText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748b',
  },
  commentRepliesList: {
    marginTop: 8,
  },
  commentEmptyText: {
    fontSize: 12,
    color: '#94a3b8',
    textAlign: 'center',
    paddingVertical: 16,
  },
  commentInputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
    paddingBottom: Platform.OS === 'android' ? 6 : 0,
  },
  commentInput: {
    flex: 1,
    minHeight: 44,
    maxHeight: 110,
    borderWidth: 1,
    borderColor: '#ffe4ef',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 13,
    color: '#0f172a',
    backgroundColor: '#ffffff',
  },
  commentSendBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#FF6600',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    fontSize: 13,
    color: '#94a3b8',
    textAlign: 'center',
    paddingVertical: 12,
  },
  emptyText: {
    fontSize: 13,
    color: '#94a3b8',
    textAlign: 'center',
    paddingVertical: 8,
  },

  // ─── Filter Section ───────────────────────────────────────────────
  filterCard: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#ffe4ef',
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
    elevation: 2,
    shadowColor: '#FF6600',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  searchBox: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fffafc',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#ffe4ef',
    gap: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: '#1e293b',
    padding: 0,
  },
  filterToggleBtn: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#fff0f5',
    borderWidth: 1.5,
    borderColor: '#FF6600',
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterToggleBtnActive: {
    backgroundColor: '#FF6600',
    borderColor: '#FF6600',
  },
  filterBadge: {
    position: 'absolute',
    top: -5,
    right: -5,
    backgroundColor: '#FF6600',
    borderRadius: 10,
    minWidth: 16,
    height: 16,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 3,
  },
  filterBadgeText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '700',
  },
  activeChipsRow: {
    marginTop: 10,
  },
  activeChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FF6600',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginRight: 6,
  },
  activeChipText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '600',
  },
  clearAllChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fef2f2',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: '#F9C8A8',
    marginRight: 6,
  },
  clearAllText: {
    color: '#ef4444',
    fontSize: 12,
    fontWeight: '600',
  },
  filterPanel: {
    marginTop: 14,
    borderTopWidth: 1,
    borderTopColor: '#ffe4ef',
    paddingTop: 14,
    gap: 14,
  },
  filterGroup: {
    gap: 8,
  },
  filterLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FF6600',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  textFilterBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fffafc',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#ffe4ef',
    gap: 6,
  },
  textFilterInput: {
    flex: 1,
    fontSize: 14,
    color: '#1e293b',
    padding: 0,
  },
  chipsRow: {
    flexDirection: 'row',
    gap: 6,
    paddingVertical: 2,
  },
  filterChip: {
    paddingHorizontal: 13,
    paddingVertical: 7,
    borderRadius: 20,
    backgroundColor: '#fffafc',
    borderWidth: 1.5,
    borderColor: '#ffe4ef',
  },
  filterChipActive: {
    backgroundColor: '#FF6600',
    borderColor: '#FF6600',
  },
  filterChipText: {
    fontSize: 13,
    color: '#94a3b8',
    fontWeight: '500',
  },
  filterChipTextActive: {
    color: '#ffffff',
    fontWeight: '700',
  },
  dropdownWrapper: {
    position: 'relative',
    zIndex: 999,
  },
  dropdownBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fffafc',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 11,
    borderWidth: 1,
    borderColor: '#ffe4ef',
  },
  dropdownBtnActive: {
    backgroundColor: '#FF6600',
    borderColor: '#FF6600',
  },
  dropdownBtnText: {
    fontSize: 14,
    color: '#64748b',
    flex: 1,
    marginRight: 6,
  },
  dropdownBtnTextActive: {
    color: '#ffffff',
    fontWeight: '600',
  },
  dropdownList: {
    position: 'absolute',
    top: 46,
    left: 0,
    right: 0,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ffe4ef',
    shadowColor: '#FF6600',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 10,
    zIndex: 1000,
  },
  dropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#fff0f5',
  },
  dropdownItemActive: {
    backgroundColor: '#fff0f5',
  },
  dropdownItemText: {
    fontSize: 14,
    color: '#334155',
  },
  dropdownItemTextActive: {
    color: '#FF6600',
    fontWeight: '600',
  },
  resetBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: '#fef2f2',
    borderWidth: 1,
    borderColor: '#ef4444',
    marginTop: 4,
  },
  resetBtnText: {
    color: '#ef4444',
    fontSize: 13,
    fontWeight: '700',
  },

  // ─── Location Tags ────────────────────────────────────────────────
  locationTagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 5,
    marginBottom: 8,
    marginTop: 2,
  },
  locationTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#fff0f5',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#ffe4ef',
  },
  locationTagText: {
    fontSize: 11,
    color: '#FF6600',
    fontWeight: '600',
  },

  // ─── Image Placeholder ───────────────────────────────────────────
  imagePlaceholder: {
    backgroundColor: '#ffe4ef',
    borderRadius: 8,
  },

  // ─── Chip Icon Spacing ────────────────────────────────────────────
  chipIcon: {
    marginLeft: 4,
  },

  // ─── Dropdown Scroll ─────────────────────────────────────────────
  dropdownScroll: {
    maxHeight: 200,
  },

  // ─── Edit Modal Sheet ─────────────────────────────────────────────
  editModalSheet: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 18,
    maxHeight: '92%',
  },
  editModalScroll: {
    paddingVertical: 4,
  },
  editInputMultiline: {
    borderWidth: 1,
    borderColor: '#ffe4ef',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 11,
    fontSize: 14,
    color: '#0f172a',
    marginBottom: 12,
    backgroundColor: '#fffafc',
    minHeight: 100,
    textAlignVertical: 'top',
  },
  addNewsButtonDisabled: {
    opacity: 0.6,
  },

  // ─── Comment List Content ─────────────────────────────────────────
  commentListContent: {
    paddingBottom: 10,
  },
  commentMiniBtnDeleteText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#ef4444',
  },

  // ─── Empty State ──────────────────────────────────────────────────
  emptyState: {
    alignItems: 'center',
    paddingVertical: 36,
    gap: 10,
  },
  emptyResetBtn: {
    marginTop: 6,
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: '#FF6600',
    borderRadius: 20,
  },
  emptyResetText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
});

export default NewsFeedStyles;
