import { StyleSheet } from 'react-native';

const UserPublicProfileStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    backgroundColor: '#ffffff',
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f1f5f9',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  menuBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  topBarTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0f172a',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 96,
  },
  profileCard: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 18,
    padding: 16,
    backgroundColor: '#ffffff',
  },
  profileTopRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
  },
  avatarWrap: {
    width: 136,
    height: 136,
    borderRadius: 68,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f1f5f9',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  avatar: {
    width: 126,
    height: 126,
    borderRadius: 63,
    backgroundColor: '#e2e8f0',
  },
  verifiedOnAvatar: {
    position: 'absolute',
    right: 8,
    bottom: 8,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#16a34a',
    borderWidth: 2,
    borderColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileMain: {
    flex: 1,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  name: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0f172a',
    maxWidth: 220,
  },
  premiumBadge: {
    marginTop: 2,
  },
  verifiedBadge: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#2563eb',
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationLine: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  locationLineText: {
    flex: 1,
    fontSize: 13,
    color: '#0f172a',
    fontWeight: '700',
  },
  rolePill: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    alignSelf: 'flex-start',
    backgroundColor: '#dbeafe',
    borderWidth: 1,
    borderColor: '#93c5fd',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  rolePillText: {
    fontSize: 13,
    fontWeight: '900',
    color: '#1d4ed8',
  },
  seatPill: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    alignSelf: 'flex-start',
    backgroundColor: '#f1f5f9',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  seatPillText: {
    fontSize: 13,
    fontWeight: '900',
    color: '#0f172a',
  },
  bioInline: {
    marginTop: 12,
    fontSize: 16,
    lineHeight: 22,
    color: '#0f172a',
    fontWeight: '600',
  },
  metricsRow: {
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 18,
  },
  metricBox: {
    flex: 1,
  },
  metricValue: {
    fontSize: 22,
    fontWeight: '900',
    color: '#0f172a',
    marginBottom: 2,
  },
  metricLabel: {
    fontSize: 12,
    color: '#64748b',
    fontWeight: '800',
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  metaPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 7,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: '#eff6ff',
    borderWidth: 1,
    borderColor: '#bfdbfe',
    maxWidth: 280,
  },
  metaPillAlt: {
    backgroundColor: '#f0fdf9',
    borderColor: '#99f6e4',
  },
  metaPillText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#1d4ed8',
  },
  metaPillTextAlt: {
    color: '#0f766e',
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 10,
  },
  locationText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748b',
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 999,
  },
  emailText: {
    fontSize: 12,
    color: '#94a3b8',
    textAlign: 'center',
  },
  loadingText: {
    marginTop: 10,
    fontSize: 12,
    color: '#64748b',
    textAlign: 'center',
    fontWeight: '600',
  },
  actionRow: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    flexWrap: 'wrap',
  },
  subscribeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#0b1220',
    borderRadius: 14,
    paddingVertical: 11,
    paddingHorizontal: 14,
    flex: 1,
    justifyContent: 'center',
    minWidth: 160,
  },
  subscribeBtnText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '900',
  },
  shareBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#0f172a',
    borderRadius: 14,
    paddingVertical: 11,
    paddingHorizontal: 14,
    flex: 1,
    justifyContent: 'center',
    minWidth: 160,
  },
  shareBtnText: {
    color: '#0f172a',
    fontSize: 13,
    fontWeight: '900',
  },
  bioCard: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 18,
    padding: 16,
    backgroundColor: '#ffffff',
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '900',
    color: '#0f172a',
    marginBottom: 8,
  },
  mutedText: {
    fontSize: 13,
    color: '#64748b',
    lineHeight: 20,
    fontWeight: '600',
  },
  bioText: {
    fontSize: 13,
    lineHeight: 20,
    color: '#475569',
  },
  tabsRow: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  tabBtn: {
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#ffffff',
  },
  tabBtnActive: {
    borderColor: '#0f172a',
  },
  tabText: {
    fontSize: 13,
    fontWeight: '900',
    color: '#94a3b8',
  },
  tabTextActive: {
    color: '#0f172a',
  },
  activityCard: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 18,
    padding: 16,
    backgroundColor: '#ffffff',
  },
  feedCard: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 18,
    padding: 14,
    backgroundColor: '#ffffff',
  },
  feedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  feedAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#e2e8f0',
  },
  feedHeaderMain: {
    flex: 1,
  },
  feedNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 2,
  },
  feedRoleMiniPill: {
    backgroundColor: '#dbeafe',
    borderWidth: 1,
    borderColor: '#93c5fd',
    borderRadius: 8,
    paddingVertical: 3,
    paddingHorizontal: 8,
  },
  feedRoleMiniText: {
    fontSize: 10,
    fontWeight: '900',
    color: '#1d4ed8',
  },
  feedName: {
    flex: 1,
    fontSize: 13,
    fontWeight: '900',
    color: '#0f172a',
  },
  feedMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  feedMetaText: {
    fontSize: 12,
    color: '#64748b',
    fontWeight: '700',
    maxWidth: 200,
  },
  feedMetaDot: {
    fontSize: 12,
    color: '#cbd5e1',
    fontWeight: '900',
  },
  feedTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0f172a',
    lineHeight: 26,
    marginBottom: 10,
  },
  feedDescription: {
    fontSize: 14,
    color: '#334155',
    lineHeight: 20,
    fontWeight: '500',
  },
  feedImage: {
    width: '100%',
    height: 220,
    borderRadius: 16,
    backgroundColor: '#e2e8f0',
    marginBottom: 10,
  },
  feedVideoBox: {
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#0b1220',
    marginBottom: 10,
  },
  feedVideo: {
    width: '100%',
    height: 240,
  },
  feedGalleryScroll: {
    marginBottom: 10,
  },
  feedGalleryRow: {
    flexDirection: 'row',
    gap: 10,
  },
  feedGalleryThumb: {
    width: 92,
    height: 66,
    borderRadius: 14,
    backgroundColor: '#e2e8f0',
  },
  feedStatusPill: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    backgroundColor: '#fef3c7',
    borderWidth: 1,
    borderColor: '#fcd34d',
    paddingVertical: 4,
    paddingHorizontal: 10,
    marginBottom: 10,
  },
  feedStatusText: {
    fontSize: 10,
    fontWeight: '900',
    color: '#92400e',
    letterSpacing: 0.6,
  },
  feedActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 18,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    paddingTop: 10,
  },
  feedActionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  feedActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 6,
    paddingVertical: 4,
    borderRadius: 10,
  },
  feedActionButtonActive: {
    backgroundColor: '#fff1f2',
    borderWidth: 1,
    borderColor: '#fecdd3',
  },
  feedActionText: {
    fontSize: 12,
    color: '#0f172a',
    fontWeight: '800',
  },

  // Comment Modal Styles
  commentOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15,23,42,0.45)',
    justifyContent: 'flex-end',
  },
  commentSheetContainer: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  commentSheet: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 16,
    maxHeight: '70%',
  },
  commentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  commentTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0f172a',
  },
  commentList: {
    marginBottom: 12,
  },
  commentListContent: {
    paddingBottom: 20,
  },
  commentItem: {
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#f8fafc',
    marginBottom: 8,
  },
  commentTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  commentAuthor: {
    fontSize: 12,
    fontWeight: '700',
    color: '#0f172a',
  },
  commentDate: {
    fontSize: 10,
    color: '#94a3b8',
  },
  commentText: {
    fontSize: 12,
    color: '#334155',
    lineHeight: 18,
  },
  commentEditInput: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 12,
    color: '#0f172a',
    backgroundColor: '#ffffff',
    marginTop: 4,
  },
  commentActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 8,
  },
  commentActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#fee2e2',
    borderWidth: 1,
    borderColor: '#fecaca',
  },
  commentActionBtnActive: {
    backgroundColor: '#fecaca',
  },
  commentActionText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#e11d48',
  },
  commentActionTextActive: {
    color: '#b91c1c',
  },
  commentMiniBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#eff6ff',
    borderWidth: 1,
    borderColor: '#dbeafe',
  },
  commentMiniBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#2563eb',
  },
  commentEmptyText: {
    fontSize: 12,
    color: '#94a3b8',
    textAlign: 'center',
    paddingVertical: 12,
  },
  commentInputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
  },
  commentInput: {
    flex: 1,
    minHeight: 44,
    maxHeight: 110,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    color: '#0f172a',
    backgroundColor: '#ffffff',
  },
  commentSendBtn: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: '#2563eb',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Reply Styles
  commentReplyForm: {
    marginTop: 8,
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#ffffff',
  },
  commentReplyInput: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 12,
    color: '#0f172a',
    backgroundColor: '#f8fafc',
    minHeight: 40,
    maxHeight: 80,
  },
  commentReplyActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 8,
  },
  commentReplyBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: '#2563eb',
  },
  commentReplyBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#ffffff',
  },
  commentCancelBtn: {
    backgroundColor: '#f1f5f9',
  },
  commentCancelBtnText: {
    color: '#64748b',
  },
  commentReplies: {
    marginTop: 8,
    paddingLeft: 16,
    borderLeftWidth: 2,
    borderLeftColor: '#e2e8f0',
  },
  commentReplyItem: {
    padding: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#f1f5f9',
    backgroundColor: '#fafbfc',
    marginBottom: 6,
  },

  // ExpandableDescription container
  expandableContainer: {
    marginBottom: 10,
  },
  readMoreBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    marginTop: 4,
    gap: 4,
  },
  readMoreText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#2563eb',
  },
});

export default UserPublicProfileStyles;
