import { StyleSheet } from 'react-native';

const UserPublicProfileStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    backgroundColor: '#ffffff',
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f1f5f9',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  menuBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  topBarTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#0f172a',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 96,
  },
  profileCard: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 18,
    padding: 16,
    backgroundColor: '#ffffff',
  },
  profileTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  avatarWrap: {
    width: 96,
    height: 96,
    borderRadius: 48,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f1f5f9',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  avatar: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: '#e2e8f0',
  },
  verifiedOnAvatar: {
    position: 'absolute',
    right: 6,
    bottom: 6,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#16a34a',
    borderWidth: 2,
    borderColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileMain: {
    flex: 1,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  name: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0f172a',
    maxWidth: 220,
  },
  premiumBadge: {
    marginTop: 2,
  },
  verifiedBadge: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#2563eb',
    alignItems: 'center',
    justifyContent: 'center',
  },
  locationLine: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  locationLineText: {
    flex: 1,
    fontSize: 13,
    color: '#0f172a',
    fontWeight: '700',
  },
  rolePill: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    alignSelf: 'flex-start',
    backgroundColor: '#dbeafe',
    borderWidth: 1,
    borderColor: '#93c5fd',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  rolePillText: {
    fontSize: 13,
    fontWeight: '900',
    color: '#1d4ed8',
  },
  seatPill: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    alignSelf: 'flex-start',
    backgroundColor: '#f1f5f9',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  seatPillText: {
    fontSize: 13,
    fontWeight: '900',
    color: '#0f172a',
  },
  bioInline: {
    marginTop: 12,
    fontSize: 16,
    lineHeight: 22,
    color: '#0f172a',
    fontWeight: '600',
  },
  metricsRow: {
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 18,
  },
  metricBox: {
    flex: 1,
  },
  metricValue: {
    fontSize: 22,
    fontWeight: '900',
    color: '#0f172a',
    marginBottom: 2,
  },
  metricLabel: {
    fontSize: 12,
    color: '#64748b',
    fontWeight: '800',
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  metaPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 7,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: '#eff6ff',
    borderWidth: 1,
    borderColor: '#bfdbfe',
    maxWidth: 280,
  },
  metaPillAlt: {
    backgroundColor: '#f0fdf9',
    borderColor: '#99f6e4',
  },
  metaPillText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#1d4ed8',
  },
  metaPillTextAlt: {
    color: '#0f766e',
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 10,
  },
  locationText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748b',
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 999,
  },
  emailText: {
    fontSize: 12,
    color: '#94a3b8',
    textAlign: 'center',
  },
  loadingText: {
    marginTop: 10,
    fontSize: 12,
    color: '#64748b',
    textAlign: 'center',
    fontWeight: '600',
  },
  actionRow: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    flexWrap: 'wrap',
  },
  subscribeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#0b1220',
    borderRadius: 14,
    paddingVertical: 11,
    paddingHorizontal: 14,
    flex: 1,
    justifyContent: 'center',
    minWidth: 160,
  },
  subscribeBtnText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '900',
  },
  shareBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#0f172a',
    borderRadius: 14,
    paddingVertical: 11,
    paddingHorizontal: 14,
    flex: 1,
    justifyContent: 'center',
    minWidth: 160,
  },
  shareBtnText: {
    color: '#0f172a',
    fontSize: 13,
    fontWeight: '900',
  },
  bioCard: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 18,
    padding: 16,
    backgroundColor: '#ffffff',
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '900',
    color: '#0f172a',
    marginBottom: 8,
  },
  mutedText: {
    fontSize: 13,
    color: '#64748b',
    lineHeight: 20,
    fontWeight: '600',
  },
  bioText: {
    fontSize: 13,
    lineHeight: 20,
    color: '#475569',
  },
  tabsRow: {
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  tabBtn: {
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#ffffff',
  },
  tabBtnActive: {
    borderColor: '#0f172a',
  },
  tabText: {
    fontSize: 13,
    fontWeight: '900',
    color: '#94a3b8',
  },
  tabTextActive: {
    color: '#0f172a',
  },
  activityCard: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 18,
    padding: 16,
    backgroundColor: '#ffffff',
  },
  feedCard: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 18,
    padding: 14,
    backgroundColor: '#ffffff',
  },
  feedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  feedAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#e2e8f0',
  },
  feedHeaderMain: {
    flex: 1,
  },
  feedNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 2,
  },
  feedRoleMiniPill: {
    backgroundColor: '#dbeafe',
    borderWidth: 1,
    borderColor: '#93c5fd',
    borderRadius: 8,
    paddingVertical: 3,
    paddingHorizontal: 8,
  },
  feedRoleMiniText: {
    fontSize: 10,
    fontWeight: '900',
    color: '#1d4ed8',
  },
  feedName: {
    flex: 1,
    fontSize: 13,
    fontWeight: '900',
    color: '#0f172a',
  },
  feedMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  feedMetaText: {
    fontSize: 12,
    color: '#64748b',
    fontWeight: '700',
    maxWidth: 200,
  },
  feedMetaDot: {
    fontSize: 12,
    color: '#cbd5e1',
    fontWeight: '900',
  },
  feedTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#0f172a',
    lineHeight: 26,
    marginBottom: 10,
  },
  feedImage: {
    width: '100%',
    height: 220,
    borderRadius: 16,
    backgroundColor: '#e2e8f0',
    marginBottom: 10,
  },
  feedVideoBox: {
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#0b1220',
    marginBottom: 10,
  },
  feedVideo: {
    width: '100%',
    height: 240,
  },
  feedStatusPill: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    backgroundColor: '#fef3c7',
    borderWidth: 1,
    borderColor: '#fcd34d',
    paddingVertical: 4,
    paddingHorizontal: 10,
    marginBottom: 10,
  },
  feedStatusText: {
    fontSize: 10,
    fontWeight: '900',
    color: '#92400e',
    letterSpacing: 0.6,
  },
  feedActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 18,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    paddingTop: 10,
  },
  feedActionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  feedActionText: {
    fontSize: 12,
    color: '#0f172a',
    fontWeight: '800',
  },
});

export default UserPublicProfileStyles;
